import type { CarpoolContent } from "./types";

export const carpoolEn: CarpoolContent = {
  meta: {
    title: "Carpool · UX research case study · UrsoParvo Studio",
    description:
      "An internal shared-fleet service. The interface had real usability problems, but research showed a larger constraint: vehicles could appear bookable without being available or ready.",
  },
  disclosure:
    "Client and product details have been anonymised. Interfaces were reconstructed for portfolio purposes and are not production screenshots.",
  labels: {
    research: "Research evidence",
    context: "Project context",
    inference: "Interpretation",
    reconstruction: "Reconstruction",
    exploration: "Design exploration",
  },
  ui: {
    stepControls: "Step through the scene",
    reconstructedUi: "Reconstructed interface",
    stateAvailable: "Available",
    statePreparing: "Preparing",
    stateReady: "Ready",
    stateCancelled: "Cancelled",
    stateAttention: "Attention",
    vehicleNames: ["Compact EV 01", "Compact EV 02", "Estate hybrid 01"],
  },
  hero: {
    eyebrow: "Carpool · Internal product · UX research",
    title: "When a reservation\nisn’t really\na reservation.",
    lead: "An internal shared-fleet service for employees. The interface had real usability problems. But research revealed a larger constraint: vehicles could appear bookable without necessarily being available or ready to use.",
    visual: {
      vehicle: "Compact EV 01",
      date: "Sat 14",
      free: "Free slot",
      states: ["Charging", "Inspection", "Maintenance", "Ready"],
      caption:
        "The availability layer people saw, and the operational states that sat underneath it.",
    },
  },
  assumption: {
    kicker: "01 · The apparent problem",
    statement: "We thought the platform was the problem.",
    chain: ["Platform", "Booking", "Car"],
    reveal: "Service",
    verdict: "Reasonable. Incomplete.",
    note: "A booking screen is where frustration shows up. It is not always where the constraint lives.",
  },
  research: {
    kicker: "02 · Research changed the problem",
    headline: "What people described was not a button problem.",
    statements: [
      "Vehicles were difficult to find.",
      "People planned months ahead.",
      "A booking could disappear before the trip.",
      "Availability was not always readiness.",
    ],
    methodsTitle: "Methods",
    methods: ["Contextual inquiry", "Leisure interviews", "Personas", "Expert review"],
    caveat: "Not analytics. No invented rates.",
    sample:
      "Qualitative evidence. Strongest on leisure use; work bookings and deeper operations were flagged as next steps.",
  },
  finding: {
    kicker: "03 · Finding a car",
    headline: "The problem wasn’t finding the Reserve button.",
    lead: "People were hunting for free days, planning months in advance and still encountering options that appeared selectable but were not actually usable.",
    mock: {
      title: "Find a vehicle",
      selectDay: "Select a day",
      days: ["Fri 12", "Sat 13", "Sun 14", "Mon 15", "Tue 16", "Wed 17"],
      states: [
        { free: 1, listed: 1, preparing: 1 },
        { free: 0, listed: 2, preparing: 1 },
        { free: 0, listed: 1, preparing: 2 },
        { free: 2, listed: 1, preparing: 0 },
        { free: 0, listed: 3, preparing: 0 },
        { free: 1, listed: 0, preparing: 2 },
      ],
      usable: "Usable",
      listed: "Listed · not bookable",
      preparing: "Listed · not ready",
      empty: "No usable vehicle on this day",
      tryAnotherDay: "Try another day",
      punch: "A free-looking list is not the same as a car you can take.",
    },
  },
  wait: {
    kicker: "04 · The wait",
    headline: "A booking could disappear before the trip.",
    caseLabel: "Documented leisure research case",
    months: [
      { month: "Jan", text: "Reservation made" },
      { month: "Mar", text: "Still booked" },
      { month: "Jun", text: "Still booked" },
      { month: "Aug", text: "~20 days before" },
      { month: "Sep", text: "Cancelled" },
    ],
    booked: "Booked",
    cancelled: "Cancelled",
    noExplanation: "No useful explanation.",
    noAlternative: "No alternative.",
    alternativeEmpty: "Alternative: none",
    note: "One documented case from leisure-user research. Not a cancellation rate. Not a system rule.",
    stage: { vehicle: "Compact EV 02", forLabel: "for September" },
  },
  readiness: {
    kicker: "05 · Availability ≠ readiness",
    statement: "Available ≠ ready",
    calendarTitle: "Calendar",
    calendarFree: "Free cell",
    steps: [
      { key: "return", label: "Return", text: "The previous user brings the vehicle back." },
      { key: "inspection", label: "Inspection", text: "Condition is checked before the next use." },
      { key: "charging", label: "Charging", text: "Electric leisure cars need charge time." },
      { key: "ready", label: "Ready", text: "Only now is the slot genuinely usable." },
    ],
    line: "A free cell in the calendar could still represent a vehicle that could not leave yet.",
    note: "Conceptual sequence from the research. No charging durations or operational SLAs are implied.",
  },
  service: {
    kicker: "06 · The service model",
    statement: "A booking is only one node in the service.",
    nodes: [
      "Request",
      "Booking",
      "Vehicle",
      "Preparation",
      "Ready",
      "Pickup",
      "Use",
      "Return",
      "Inspection",
      "Next user",
    ],
    focus: [1, 2, 3, 4],
    focusCaptions: [
      "The product lived here. Booking was the part people could see.",
      "Behind it sat a physical vehicle, with a state of its own.",
      "Preparation, charging and maintenance decided whether that vehicle could move.",
      "Ready is an operational fact. The calendar could only imply it.",
    ],
    note: "Conceptual service model derived from the research. Not an official SOP.",
  },
  intents: {
    kicker: "07 · Work ≠ leisure",
    headline: "Two intentions, one way to book.",
    work: {
      label: "Work",
      traits: ["Fixed commitment", "Specific date", "Precise interval"],
      query: "I need a vehicle on 14 September.",
      result: "Search a fixed date and time window.",
    },
    leisure: {
      label: "Leisure",
      traits: ["Next usable opportunity", "Flexible", "Weekends matter"],
      query: "Show me the next usable weekend.",
      result: "Search forward for the next usable opportunity.",
    },
    recommendation: "The research recommended declaring intent.",
    caveat: "Not a claim that the product already split these flows. This is a design exploration.",
  },
  rules: {
    kicker: "08 · Rules too late",
    headline: "The system knew the rule before the click.",
    before: { label: "Before", steps: ["Reserve", "Rule appears"] },
    after: {
      label: "Exploration",
      steps: ["Rule", "Confirm eligibility", "Reserve"],
    },
    rule: "You already have an active leisure reservation.",
    ruleEarly: "One active leisure reservation at a time. Yours ends 21 Sep.",
    point: "Limits such as one active leisure reservation appeared after Reserve, not before commitment.",
    note: "Documented in the expert review. The earlier placement is an exploration, not a shipped change.",
  },
  history: {
    kicker: "09 · Booking history",
    headline: "Status was hard to see when it mattered.",
    problem:
      "Default filters could hide future bookings, and important state appeared late. People opened tickets for reservations that already existed.",
    exploration:
      "Make future bookings and the current state immediately visible, before anyone has to ask.",
    views: { original: "Original default", exploration: "Exploration" },
    hiddenHint: "1 upcoming booking not shown by the default filter",
    nextLabel: "Next booking",
    tabs: ["Upcoming", "Active", "Completed", "Cancelled"],
    booking: {
      vehicle: "Compact EV 01",
      when: "Sat 14 Sep · 09:00 to 18:00",
      pastWhen: "Fri 22 Aug · 09:00 to 13:00",
      statuses: ["Confirmed", "In use", "Completed", "Cancelled"],
    },
    empty: "Nothing to show",
    note: "The source documents the tickets. It does not claim any reduction in them.",
  },
  usage: {
    kicker: "10 · Scheduled ≠ actual",
    headline: "Scheduled time is not proof of what happened.",
    scheduled: { label: "Scheduled", pickup: "09:00", ret: "17:00" },
    actual: { label: "Actual", pickup: "09:18", ret: "16:42" },
    pickup: "Pickup",
    ret: "Return",
    illustrative: "Illustrative times",
    recommendation:
      "The research recommended capturing actual pickup and return times, for accountability when plans change.",
  },
  pivot: {
    kicker: "11 · The pivot",
    lines: [
      "The interface had real problems.",
      "But usability was secondary.",
      "The dominant constraint was vehicle availability.",
      "The problem changed.",
    ],
    fromLabel: "From",
    from: "How do we improve the booking?",
    toLabel: "To",
    to: "What makes a booking real?",
  },
  software: {
    kicker: "12 · What software can and cannot do",
    headline: "The product could improve visibility. It could not create capacity.",
    can: {
      title: "Software can help with",
      items: [
        "Availability discovery",
        "Earlier rules",
        "Status and confirmation",
        "History",
        "Cancellation reasons",
        "Readiness signals, if data exists",
        "Work / leisure intent",
      ],
    },
    cannot: {
      title: "Software cannot do alone",
      items: [
        "Create fleet capacity",
        "Remove charging",
        "Create inspection capacity",
        "Prevent all maintenance cancellations",
        "Make scarcity disappear",
      ],
    },
  },
  investment: {
    kicker: "13 · Strategic implication",
    headline: "If a platform takes 6 to 12 months, what problem is that investment solving?",
    contextNote:
      "“6 to 12 months” is context of the project, not a research metric. No ROI is calculated here.",
    a: { title: "The plan", items: ["New platform", "Better booking UI"] },
    b: {
      title: "The constraint",
      items: ["Same fleet", "Same availability constraint"],
    },
    insight: "Better access to the same constrained capacity is still constrained capacity.",
  },
  closing: {
    kicker: "14 · What stayed",
    lines: [
      "The platform was only one layer of the problem.",
      "Tell the truth about availability earlier.",
      "Only rebuild when the rebuild addresses the dominant constraint.",
    ],
  },
};
