import type { CarpoolContent } from "./types";

export const carpoolPt: CarpoolContent = {
  meta: {
    title: "Carpool · caso de estudo de UX research · UrsoParvo Studio",
    description:
      "Um serviço interno de frota partilhada. A interface tinha problemas reais de usabilidade, mas a pesquisa mostrou uma restrição maior: veículos podiam parecer reserváveis sem estarem disponíveis ou prontos.",
  },
  disclosure:
    "Detalhes de cliente e produto foram anonimizados. As interfaces foram reconstruídas para efeitos de portfólio e não são capturas de produção.",
  labels: {
    research: "Evidência de pesquisa",
    context: "Contexto de projecto",
    inference: "Interpretação",
    reconstruction: "Reconstrução",
    exploration: "Exploração de design",
  },
  ui: {
    stepControls: "Percorrer a cena",
    reconstructedUi: "Interface reconstruída",
    stateAvailable: "Disponível",
    statePreparing: "Em preparação",
    stateReady: "Pronto",
    stateCancelled: "Cancelada",
    stateAttention: "Atenção",
    vehicleNames: ["Compact EV 01", "Compact EV 02", "Estate hybrid 01"],
  },
  hero: {
    eyebrow: "Carpool · Produto interno · UX research",
    title: "Quando uma reserva\nnão é bem\numa reserva.",
    lead: "Um serviço interno de frota partilhada para colaboradores. A interface tinha problemas reais de usabilidade. Mas a pesquisa revelou uma restrição maior: os veículos podiam parecer reserváveis sem estarem necessariamente disponíveis ou prontos a usar.",
    visual: {
      vehicle: "Compact EV 01",
      date: "Sáb 14",
      free: "Slot livre",
      states: ["Carregamento", "Inspeção", "Manutenção", "Pronto"],
      caption:
        "A camada de disponibilidade que as pessoas viam, e os estados operacionais que ficavam por baixo.",
    },
  },
  assumption: {
    kicker: "01 · O problema aparente",
    statement: "Pensávamos que a plataforma era o problema.",
    chain: ["Plataforma", "Reserva", "Carro"],
    reveal: "Serviço",
    verdict: "Razoável. Incompleto.",
    note: "Um ecrã de reserva é onde a frustração aparece. Nem sempre é onde a restrição vive.",
  },
  research: {
    kicker: "02 · A pesquisa mudou o problema",
    headline: "O que as pessoas descreviam não era um problema de botão.",
    statements: [
      "Os veículos eram difíceis de encontrar.",
      "As pessoas planeavam com meses de antecedência.",
      "Uma reserva podia desaparecer antes da viagem.",
      "Disponibilidade nem sempre era readiness.",
    ],
    methodsTitle: "Métodos",
    methods: ["Contextual inquiry", "Entrevistas de lazer", "Personas", "Expert review"],
    caveat: "Não é analytics. Sem taxas inventadas.",
    sample:
      "Evidência qualitativa. Mais forte no uso de lazer; reservas de trabalho e operações mais profundas ficaram como próximos passos.",
  },
  finding: {
    kicker: "03 · Encontrar um carro",
    headline: "O problema não era encontrar o botão Reservar.",
    lead: "As pessoas caçavam dias livres, planeavam com meses de antecedência e ainda assim encontravam opções que pareciam seleccionáveis mas não eram, de facto, utilizáveis.",
    mock: {
      title: "Encontrar um veículo",
      selectDay: "Escolher um dia",
      days: ["Sex 12", "Sáb 13", "Dom 14", "Seg 15", "Ter 16", "Qua 17"],
      states: [
        { free: 1, listed: 1, preparing: 1 },
        { free: 0, listed: 2, preparing: 1 },
        { free: 0, listed: 1, preparing: 2 },
        { free: 2, listed: 1, preparing: 0 },
        { free: 0, listed: 3, preparing: 0 },
        { free: 1, listed: 0, preparing: 2 },
      ],
      usable: "Utilizável",
      listed: "Listado · não reservável",
      preparing: "Listado · não pronto",
      empty: "Sem veículo utilizável neste dia",
      tryAnotherDay: "Experimentar outro dia",
      punch: "Uma lista que parece livre não é o mesmo que um carro que se pode levar.",
    },
  },
  wait: {
    kicker: "04 · A espera",
    headline: "Uma reserva podia desaparecer antes da viagem.",
    caseLabel: "Caso documentado da pesquisa de lazer",
    months: [
      { month: "Jan", text: "Reserva feita" },
      { month: "Mar", text: "Ainda reservado" },
      { month: "Jun", text: "Ainda reservado" },
      { month: "Ago", text: "~20 dias antes" },
      { month: "Set", text: "Cancelada" },
    ],
    booked: "Reservado",
    cancelled: "Cancelada",
    noExplanation: "Sem explicação útil.",
    noAlternative: "Sem alternativa.",
    alternativeEmpty: "Alternativa: nenhuma",
    note: "Um caso documentado da pesquisa com utilizadores de lazer. Não é uma taxa de cancelamento. Não é uma regra do sistema.",
    stage: { vehicle: "Compact EV 02", forLabel: "para setembro" },
  },
  readiness: {
    kicker: "05 · Disponibilidade ≠ readiness",
    statement: "Disponível ≠ pronto",
    calendarTitle: "Calendário",
    calendarFree: "Célula livre",
    steps: [
      { key: "return", label: "Devolução", text: "O utilizador anterior devolve o veículo." },
      { key: "inspection", label: "Inspeção", text: "A condição é verificada antes do uso seguinte." },
      { key: "charging", label: "Carregamento", text: "Os carros eléctricos de lazer precisam de tempo de carga." },
      { key: "ready", label: "Pronto", text: "Só agora o slot é genuinamente utilizável." },
    ],
    line: "Uma célula livre no calendário podia ainda representar um veículo que não podia sair.",
    note: "Sequência conceptual a partir da pesquisa. Não se implicam durações de carregamento nem SLAs operacionais.",
  },
  service: {
    kicker: "06 · O modelo de serviço",
    statement: "Uma reserva é só um nó do serviço.",
    nodes: [
      "Pedido",
      "Reserva",
      "Veículo",
      "Preparação",
      "Pronto",
      "Levantamento",
      "Uso",
      "Devolução",
      "Inspeção",
      "Próximo utilizador",
    ],
    focus: [1, 2, 3, 4],
    focusCaptions: [
      "O produto vivia aqui. A reserva era a parte que as pessoas viam.",
      "Por trás havia um veículo físico, com um estado próprio.",
      "Preparação, carregamento e manutenção decidiam se esse veículo podia andar.",
      "Pronto é um facto operacional. O calendário só o podia sugerir.",
    ],
    note: "Modelo conceptual de serviço derivado da pesquisa. Não é um SOP oficial.",
  },
  intents: {
    kicker: "07 · Trabalho ≠ lazer",
    headline: "Duas intenções, uma só forma de reservar.",
    work: {
      label: "Trabalho",
      traits: ["Compromisso fixo", "Data específica", "Intervalo preciso"],
      query: "Preciso de um veículo a 14 de setembro.",
      result: "Procurar uma data e janela horária fixas.",
    },
    leisure: {
      label: "Lazer",
      traits: ["Próxima oportunidade utilizável", "Flexível", "Fins-de-semana importam"],
      query: "Mostra-me o próximo fim-de-semana utilizável.",
      result: "Procurar em frente a próxima oportunidade utilizável.",
    },
    recommendation: "A pesquisa recomendou declarar a intenção.",
    caveat: "Não se afirma que o produto já separava estes fluxos. Isto é uma exploração de design.",
  },
  rules: {
    kicker: "08 · Regras demasiado tarde",
    headline: "O sistema conhecia a regra antes do clique.",
    before: { label: "Antes", steps: ["Reservar", "A regra aparece"] },
    after: {
      label: "Exploração",
      steps: ["Regra", "Confirmar elegibilidade", "Reservar"],
    },
    rule: "Já tem uma reserva de lazer activa.",
    ruleEarly: "Uma reserva de lazer activa de cada vez. A sua termina a 21 Set.",
    point: "Limites como uma reserva de lazer activa apareciam depois de Reservar, não antes do compromisso.",
    note: "Documentado no expert review. A colocação mais cedo é uma exploração, não uma alteração publicada.",
  },
  history: {
    kicker: "09 · Histórico de reservas",
    headline: "O estado era difícil de ver quando importava.",
    problem:
      "Filtros por defeito podiam esconder reservas futuras, e o estado importante aparecia tarde. As pessoas abriam tickets para reservas que já existiam.",
    exploration:
      "Tornar as reservas futuras e o estado actual imediatamente visíveis, antes de alguém ter de perguntar.",
    views: { original: "Default original", exploration: "Exploração" },
    hiddenHint: "1 reserva futura não mostrada pelo filtro por defeito",
    nextLabel: "Próxima reserva",
    tabs: ["Próximas", "Activas", "Concluídas", "Canceladas"],
    booking: {
      vehicle: "Compact EV 01",
      when: "Sáb 14 Set · 09:00 a 18:00",
      pastWhen: "Sex 22 Ago · 09:00 a 13:00",
      statuses: ["Confirmada", "Em uso", "Concluída", "Cancelada"],
    },
    empty: "Nada a mostrar",
    note: "A fonte documenta os tickets. Não afirma qualquer redução dos mesmos.",
  },
  usage: {
    kicker: "10 · Agendado ≠ real",
    headline: "A hora agendada não prova o que aconteceu.",
    scheduled: { label: "Agendado", pickup: "09:00", ret: "17:00" },
    actual: { label: "Real", pickup: "09:18", ret: "16:42" },
    pickup: "Levantamento",
    ret: "Devolução",
    illustrative: "Horários ilustrativos",
    recommendation:
      "A pesquisa recomendou registar as horas reais de levantamento e devolução, para responsabilização quando os planos mudam.",
  },
  pivot: {
    kicker: "11 · A viragem",
    lines: [
      "A interface tinha problemas reais.",
      "Mas a usabilidade era secundária.",
      "A restrição dominante era a disponibilidade de veículos.",
      "O problema mudou.",
    ],
    fromLabel: "De",
    from: "Como melhoramos a reserva?",
    toLabel: "Para",
    to: "O que torna uma reserva verdadeira?",
  },
  software: {
    kicker: "12 · O que o software pode e não pode",
    headline: "O produto podia melhorar a visibilidade. Não podia criar capacidade.",
    can: {
      title: "O software pode ajudar com",
      items: [
        "Descoberta de disponibilidade",
        "Regras mais cedo",
        "Estado e confirmação",
        "Histórico",
        "Motivos de cancelamento",
        "Sinais de readiness, se houver dados",
        "Intenção trabalho / lazer",
      ],
    },
    cannot: {
      title: "O software não pode sozinho",
      items: [
        "Criar capacidade de frota",
        "Eliminar o carregamento",
        "Criar capacidade de inspeção",
        "Impedir todos os cancelamentos de manutenção",
        "Fazer a escassez desaparecer",
      ],
    },
  },
  investment: {
    kicker: "13 · Implicação estratégica",
    headline: "Se uma plataforma leva 6 a 12 meses, que problema está esse investimento a resolver?",
    contextNote:
      "“6 a 12 meses” é contexto do projecto, não uma métrica de pesquisa. Não se calcula ROI aqui.",
    a: { title: "O plano", items: ["Nova plataforma", "Melhor UI de reserva"] },
    b: {
      title: "A restrição",
      items: ["Mesma frota", "Mesma restrição de disponibilidade"],
    },
    insight: "Melhor acesso à mesma capacidade limitada continua a ser capacidade limitada.",
  },
  closing: {
    kicker: "14 · O que ficou",
    lines: [
      "A plataforma era só uma camada do problema.",
      "Dizer a verdade sobre a disponibilidade mais cedo.",
      "Só reconstruir quando a reconstrução responde à restrição dominante.",
    ],
  },
};
