import type { ProjectFlowContent } from "./types";

const labels = {
  identityRedesign: "Redesign an existing brand",
  visualIdentity: "Create a visual identity",
  visualDirection: "Create a visual direction",
  specificAsset: "Create something specific",
  unsure: "I’m not sure yet",
  nameAndBusiness: "A name and a business",
  logo: "Logo / wordmark",
  fullVisualSystem: "A full visual system",
  identityNoLongerWorks: "An identity that no longer works",
  disconnectedMaterials: "Several disconnected visual materials",
  refine: "Refine",
  reimagine: "Reimagine",
  rebuild: "Rebuild",
  veryClear: "Very clear",
  mostlyClear: "Mostly clear",
  stillTakingShape: "Still taking shape",
  symbol: "Symbol / mark",
  typography: "Typography",
  colour: "Colour system",
  graphicLanguage: "Graphic language",
  illustration: "Illustration",
  iconography: "Iconography",
  photographyDirection: "Photography direction",
  layoutSystem: "Layout / composition system",
  templates: "Templates",
  packaging: "Packaging",
  signage: "Signage",
  merchandise: "Merchandise",
  other: "Other",
  foundations: "Foundations",
  system: "System",
  systemAndApplications: "System + applications",
  completeSystem: "Complete system",
  essential: "Essential",
  standard: "Standard",
  detailed: "Detailed",
  website: "Website",
  social: "Social media",
  email: "Email",
  digitalProducts: "Digital products",
  presentations: "Presentations",
  reports: "Reports",
  brochures: "Brochures",
  publications: "Publications",
  print: "Printed material",
  environment: "Environment",
  objects: "Objects",
  advertising: "Advertising",
  posters: "Posters",
  launches: "Launches",
  events: "Events",
  few: "A few key applications",
  smallSet: "A small set",
  broad: "A broad range",
  many: "Many applications across different contexts",
  eventIdentity: "Event identity",
  keyVisual: "Key visual",
  campaignLanguage: "Campaign visual language",
  posterCampaign: "Poster / print campaign",
  digitalCampaign: "Digital campaign",
  fullCommunication: "Full communication system",
  stage: "Stage / venue",
  editorial: "Editorial",
  cover: "Album / cover artwork",
  eventArtwork: "Event artwork",
  printPiece: "Print piece",
  simple: "Simple",
  developed: "Developed",
  highlyDetailed: "Highly detailed",
  "1": "1",
  "2-3": "2–3",
  "4-6": "4–6",
  "7+": "7+",
  motion: "Motion",
  film: "Film",
  photography: "Photography",
  digitalDesign: "Digital",
  development: "Development",
  "3d": "3D",
  writing: "Writing",
  spatial: "Spatial",
  noDate: "No fixed date",
  fewMonths: "Within the next few months",
  specificDate: "I have a specific date",
  quickly: "We need to move quickly",
  oneDecisionMaker: "One decision-maker",
  smallTeam: "Small team",
  severalStakeholders: "Several stakeholders",
  leadership: "Leadership / board",
  multipleOrgs: "Multiple teams or organisations",
  agencyPartner: "Agency / external partner",
  notYet: "Not yet",
  under3000: "Under €3,000",
  "3000-5000": "€3,000–€5,000",
  "5000-10000": "€5,000–€10,000",
  "10000-20000": "€10,000–€20,000",
  "20000+": "Over €20,000",
} as const;

export const en: ProjectFlowContent = {
  meta: {
    title: "Talk about a project · UrsoParvo Studio",
    description:
      "Tell us about the project. A few questions help us understand what needs to be done and give you an initial estimate.",
  },
  intro: {
    kicker: "Project",
    title: "Talk about a project",
    body: "A few questions help us understand what needs to be done and give you an initial estimate.",
  },
  nav: {
    back: "Back",
    continue: "Continue",
    skip: "Not now",
    edit: "Edit",
    talk: "Talk about the project",
    send: "Send the summary",
    sending: "Sending…",
    startAgain: "Start again",
    stepStatus: "{current} of {total}",
  },
  questions: {
    projectType: {
      kicker: "Project",
      question: "What do you need to do?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "identityRedesign",
          label: "Redesign a brand",
          description: "The brand exists, but the identity needs to change.",
        },
        {
          id: "visualIdentity",
          label: "Create a visual identity",
          description: "The brand needs a visual identity.",
        },
        {
          id: "visualDirection",
          label: "Create an image",
          description: "A campaign, event, festival or project needs a visual language.",
        },
        {
          id: "specificAsset",
          label: "Create something specific",
          description: "An illustration, poster, publication or another piece.",
        },
        {
          id: "unsure",
          label: "I’m not sure yet",
          description: "I know something needs to change, but I don’t yet know exactly what.",
        },
      ],
    },
    existingBrand: {
      kicker: "What exists",
      question: "What does the brand already have?",
      description: "You can choose more than one. If you are not sure, that is fine.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "nameAndBusiness", label: "A name and a business" },
        { id: "logo", label: "A logo" },
        { id: "visualIdentity", label: "A visual identity" },
        { id: "disconnectedMaterials", label: "Several materials that don’t quite hold together" },
        { id: "unsure", label: "I’m not sure yet" },
      ],
    },
    redesignDepth: {
      kicker: "Scope",
      question: "What needs to change?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "refine",
          label: "Refine",
          description: "The foundation works, but it needs adjusting.",
        },
        {
          id: "reimagine",
          label: "Reimagine",
          description: "The brand needs a significant visual change.",
        },
        {
          id: "rebuild",
          label: "Rebuild",
          description: "The identity no longer matches what the brand is today.",
        },
      ],
    },
    strategyClarity: {
      kicker: "Direction",
      question: "Does the brand already have a defined direction?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "veryClear", label: "Yes" },
        { id: "mostlyClear", label: "Mostly" },
        { id: "stillTakingShape", label: "We are still defining it" },
        { id: "unsure", label: "We do not know where to start" },
      ],
    },
    identityScope: {
      kicker: "Identity",
      question: "What needs to be created?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "logo", label: "Logo" },
        { id: "symbol", label: "Symbol" },
        { id: "typography", label: "Typography" },
        { id: "colour", label: "Colour" },
        { id: "graphicLanguage", label: "Graphic system" },
        { id: "illustration", label: "Illustration" },
        { id: "iconography", label: "Iconography" },
        { id: "photographyDirection", label: "Photography direction" },
        { id: "templates", label: "Templates" },
        { id: "packaging", label: "Packaging" },
        { id: "signage", label: "Signage" },
        { id: "merchandise", label: "Merchandise" },
        { id: "other", label: "Something else" },
      ],
    },
    systemDepth: {
      kicker: "Reach",
      question: "How far should the identity go?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "foundations",
          label: "Foundations",
          description: "The essential elements of the identity.",
        },
        {
          id: "system",
          label: "System",
          description: "A visual language that works in different contexts.",
        },
        {
          id: "systemAndApplications",
          label: "System + applications",
          description: "The identity and its main applications.",
        },
        {
          id: "completeSystem",
          label: "Complete system",
          description: "A system ready for continued use by a team.",
        },
      ],
    },
    guidelines: {
      kicker: "Documentation",
      question: "What documentation do you need?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "essential",
          label: labels.essential,
          description: "The rules needed to use the identity correctly.",
        },
        {
          id: "standard",
          label: labels.standard,
          description: "Rules, visual system and applications.",
        },
        {
          id: "detailed",
          label: labels.detailed,
          description: "Fuller documentation for continued use.",
        },
      ],
    },
    applications: {
      kicker: "Where it appears",
      question: "Where will it appear?",
      continueLabel: "Continue",
      backLabel: "Back",
      groups: [
        {
          id: "digital",
          label: "Digital",
          options: [
            { id: "website", label: "Website" },
            { id: "social", label: "Social media" },
            { id: "email", label: "Email" },
            { id: "presentations", label: "Presentations" },
          ],
        },
        {
          id: "editorial",
          label: "Print",
          options: [
            { id: "posters", label: "Posters" },
            { id: "brochures", label: "Brochures" },
            { id: "publications", label: "Publications" },
            { id: "packaging", label: "Packaging" },
          ],
        },
        {
          id: "physical",
          label: "Physical",
          options: [
            { id: "signage", label: "Signage" },
            { id: "environment", label: "Spaces" },
            { id: "merchandise", label: "Merchandise" },
            { id: "objects", label: "Objects" },
          ],
        },
        {
          id: "campaigns",
          label: "Campaigns",
          options: [
            { id: "advertising", label: "Advertising" },
            { id: "events", label: "Events" },
            { id: "launches", label: "Launches" },
          ],
        },
      ],
    },
    applicationScale: {
      kicker: "Scale",
      question: "How extensive are the applications?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "few", label: labels.few },
        { id: "smallSet", label: labels.smallSet },
        { id: "broad", label: labels.broad },
        { id: "many", label: labels.many },
        { id: "unsure", label: "Not sure" },
      ],
    },
    campaignKind: {
      kicker: "Campaign",
      question: "What are we creating?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "eventIdentity", label: "The visual face of an event" },
        { id: "keyVisual", label: "A main image" },
        { id: "campaignLanguage", label: "A language for the campaign" },
        { id: "posterCampaign", label: "A poster campaign" },
        { id: "digitalCampaign", label: "A digital campaign" },
        { id: "fullCommunication", label: "A full communication system" },
        { id: "other", label: "Something else" },
      ],
    },
    campaignPlacements: {
      kicker: "Where it appears",
      question: "Where will this appear?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "posters", label: "Posters" },
        { id: "social", label: "Social media" },
        { id: "website", label: "Website" },
        { id: "advertising", label: "Advertising" },
        { id: "signage", label: "Signage" },
        { id: "stage", label: "Stage / venue" },
        { id: "merchandise", label: "Merchandise" },
        { id: "editorial", label: "Print" },
        { id: "other", label: "Other" },
      ],
    },
    specificKind: {
      kicker: "Piece",
      question: "What kind of piece is this?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "illustration", label: "Illustration" },
        { id: "poster", label: "Poster" },
        { id: "editorial", label: "An image for a publication" },
        { id: "cover", label: "Cover" },
        { id: "packaging", label: "Packaging" },
        { id: "eventArtwork", label: "An image for an event" },
        { id: "printPiece", label: "Another printed piece" },
        { id: "other", label: "Something else" },
      ],
    },
    imageComplexity: {
      kicker: "Image",
      question: "How complex is the image?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "simple", label: labels.simple },
        { id: "developed", label: labels.developed },
        { id: "highlyDetailed", label: labels.highlyDetailed },
        { id: "unsure", label: "Not sure" },
      ],
    },
    pieceCount: {
      kicker: "Quantity",
      question: "How many final pieces?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "1", label: "One" },
        { id: "2-3", label: "Two or three" },
        { id: "4-6", label: "Four to six" },
        { id: "7+", label: "Seven or more" },
      ],
    },
    specialists: {
      kicker: "Around it",
      question: "Does the project need anything else?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "motion",
          label: "Motion",
          description: "Animation and movement.",
        },
        {
          id: "film",
          label: "Video",
          description: "Filming, editing or audiovisual production.",
        },
        {
          id: "photography",
          label: "Photography",
          description: "Photography or image direction.",
        },
        {
          id: "digitalDesign",
          label: "Digital",
          description: "A website or digital experience.",
        },
        {
          id: "development",
          label: "Development",
          description: "Technical implementation.",
        },
        {
          id: "advertising",
          label: "Advertising",
          description: "Campaigns and communication pieces.",
        },
        {
          id: "3d",
          label: "3D",
          description: "3D image or animation.",
        },
        {
          id: "writing",
          label: "Writing",
          description: "Naming, copy or verbal identity.",
        },
        {
          id: "spatial",
          label: "Space",
          description: "Signage or communication in a physical place.",
        },
      ],
    },
    timeline: {
      kicker: "Timeline",
      question: "Is there a date we need to meet?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "noDate", label: "No" },
        { id: "fewMonths", label: "In the coming months" },
        { id: "specificDate", label: "I have a set date" },
        { id: "quickly", label: "We need to start soon" },
      ],
    },
    targetDate: {
      kicker: "Timeline",
      question: "What is the date?",
      dateLabel: "When do you need this?",
      continueLabel: "Continue",
      backLabel: "Back",
    },
    stakeholders: {
      kicker: "People",
      question: "Who will take part in the decisions?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "oneDecisionMaker", label: "One person" },
        { id: "smallTeam", label: "A small team" },
        { id: "severalStakeholders", label: "Several people" },
        { id: "leadership", label: "Leadership" },
        { id: "multipleOrgs", label: "Several teams or organisations" },
        { id: "agencyPartner", label: "Agency / external partner" },
      ],
    },
    budget: {
      kicker: "Budget",
      question: "Do you already have a budget in mind?",
      helper: "It does not need to be exact.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "notYet", label: "Not yet" },
        { id: "under3000", label: labels.under3000 },
        { id: "3000-5000", label: labels["3000-5000"] },
        { id: "5000-10000", label: labels["5000-10000"] },
        { id: "10000-20000", label: labels["10000-20000"] },
        { id: "20000+", label: labels["20000+"] },
      ],
    },
    description: {
      kicker: "Context",
      question: "Tell us a little about the project.",
      placeholder: "What are you trying to change, create or communicate?",
      continueLabel: "Continue",
      backLabel: "Back",
    },
  },
  review: {
    kicker: "Reading",
    title: "Your project",
    empty: "Not specified",
    continueLabel: "Continue",
    sections: {
      type: "Type",
      scope: "Scope",
      applications: "Applications",
      extensions: "Extensions",
      timeline: "Timeline",
      budget: "Budget",
    },
  },
  estimate: {
    kicker: "Project",
    seeing: "Your project",
    initial: "Initial estimate",
    indicative: "Initial estimate",
    lowTitle: "It is too early to give an estimate.",
    lowBody:
      "We need to understand the project better before we can give you a useful figure.",
    rangeNote:
      "Based on what you described, this is the range we are considering for the project.",
    finalNote:
      "The final figure will be set once we understand the project in more detail.",
    specialists:
      "This project may need {list}. If so, we work with specialists in those areas.",
    talk: "Talk about the project",
    edit: "Edit",
    preparing: "Preparing…",
    scale: {
      contained: "a contained scale",
      medium: "a medium scale",
      mediumLarge: "a medium-to-large scope",
      large: "a large scope",
    },
  },
  contact: {
    kicker: "Contact",
    question: "Where should we send the summary?",
    name: "Name",
    email: "Email",
    company: "Company / organisation",
    website: "Website",
    phone: "Phone",
    optional: "optional",
    nameError: "We need a name so we know who we are speaking with.",
    emailError: "We need an email address so we can send the project summary.",
  },
  complete: {
    kicker: "Sent",
    title: "We have the project.",
    body: "We will read it and reply with the next steps.",
    home: "Back to the start",
  },
  errors: {
    submit:
      "Something prevented the project from being submitted. Your answers are still here. Please try again.",
    estimate: "The estimate could not be prepared. Your answers are still here.",
    choose: "Choose one to continue.",
  },
  classifications: {
    identityRefresh: "a visual identity refinement",
    identityRedesign: "a visual identity redesign",
    identitySystem: "a visual identity system",
    visualIdentity: "a new visual identity",
    campaignEvent: "a visual direction for an event or campaign",
    keyVisual: "a main campaign image",
    specificGraphic: "a specific graphic piece",
    needsConversation: "a project still taking shape",
  },
  assumptions: {
    scopeDescribed: "The estimate assumes the scope described above.",
    estimateNotBinding:
      "This is an initial estimate, not a quotation. The proposal is confirmed after we discuss the project.",
    strategyPartiallyDefined: "The direction appears partly defined.",
    strategyUndefined: "The direction is still taking shape.",
    specialistsIntegrated:
      "Specialist extensions can be brought into the project when they are useful.",
    discoveryRecommended: "A conversation is recommended before confirming scope and fees.",
    applicationsUncertain: "The extent of the applications is still unclear.",
    timelineFlexible: "There is no fixed date constraining the schedule.",
  },
  confidence: {
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  labels: {
    ...labels,
    visualIdentityExisting: "A visual identity",
    logoMark: "A logo",
    poster: "Poster",
    "pieces:1": "1 final piece",
    "pieces:2-3": "2–3 final pieces",
    "pieces:4-6": "4–6 final pieces",
    "pieces:7+": "7 or more final pieces",
  },
  brief: {
    project: "PROJECT",
    overview: "OVERVIEW",
    scope: "SCOPE",
    applications: "APPLICATIONS",
    extensions: "EXTENSIONS",
    timeline: "TIMELINE",
    budget: "BUDGET",
    initialEstimate: "INITIAL ESTIMATE",
    confidence: "CONFIDENCE",
    notes: "NOTES",
    contact: "CONTACT",
    none: "None",
    notSpecified: "Not specified",
    toBeDiscussed: "To be discussed",
    labels: {
      ...labels,
      visualIdentity: "Create a visual identity",
      logo: "Logo / wordmark",
      poster: "Poster",
      "pieces:1": "1 final piece",
      "pieces:2-3": "2–3 final pieces",
      "pieces:4-6": "4–6 final pieces",
      "pieces:7+": "7 or more final pieces",
      visualIdentityExisting: "A visual identity",
      logoMark: "A logo",
    },
    confidenceLabels: {
      high: "High",
      medium: "Medium",
      low: "Low",
    },
  },
  stepAria: {},
};
