import type { ProjectFlowContent } from "./types";

const labels = {
  identityRedesign: "Redesign an existing brand",
  visualIdentity: "Create a visual identity",
  visualDirection: "Create a visual direction",
  specificAsset: "Create something specific",
  unsure: "I’m not sure yet",
  nameAndBusiness: "A name and a business",
  logo: "Logo / wordmark",
  fullVisualSystem: "A full visual system",
  identityNoLongerWorks: "An identity that no longer works",
  disconnectedMaterials: "Several disconnected visual materials",
  refine: "Refine",
  reimagine: "Reimagine",
  rebuild: "Rebuild",
  veryClear: "Very clear",
  mostlyClear: "Mostly clear",
  stillTakingShape: "Still taking shape",
  symbol: "Symbol / mark",
  typography: "Typography",
  colour: "Colour system",
  graphicLanguage: "Graphic language",
  illustration: "Illustration",
  iconography: "Iconography",
  photographyDirection: "Photography direction",
  layoutSystem: "Layout / composition system",
  templates: "Templates",
  packaging: "Packaging",
  signage: "Signage",
  merchandise: "Merchandise",
  other: "Other",
  foundations: "Foundations",
  system: "System",
  systemAndApplications: "System and applications",
  completeSystem: "Complete system",
  essential: "Essential",
  standard: "Standard",
  detailed: "Detailed",
  website: "Website",
  social: "Social media",
  email: "Email",
  digitalProducts: "Digital products",
  presentations: "Presentations",
  reports: "Reports",
  brochures: "Brochures",
  publications: "Publications",
  print: "Printed material",
  environment: "Environment",
  objects: "Objects",
  advertising: "Advertising",
  posters: "Posters",
  launches: "Launches",
  events: "Events",
  few: "A few key applications",
  smallSet: "A small set",
  broad: "A broad range",
  many: "Many applications across different contexts",
  eventIdentity: "Event identity",
  keyVisual: "Key visual",
  campaignLanguage: "Campaign visual language",
  posterCampaign: "Poster / print campaign",
  digitalCampaign: "Digital campaign",
  fullCommunication: "Full communication system",
  stage: "Stage / venue",
  editorial: "Editorial",
  cover: "Album / cover artwork",
  eventArtwork: "Event artwork",
  printPiece: "Print piece",
  simple: "Simple",
  developed: "Developed",
  highlyDetailed: "Highly detailed",
  "1": "1",
  "2-3": "2–3",
  "4-6": "4–6",
  "7+": "7+",
  motion: "Motion",
  film: "Film",
  photography: "Photography",
  digitalDesign: "Digital",
  development: "Development",
  "3d": "3D",
  writing: "Writing",
  spatial: "Spatial",
  noDate: "No fixed date",
  fewMonths: "Within the next few months",
  specificDate: "I have a specific date",
  quickly: "We need to move quickly",
  oneDecisionMaker: "One decision-maker",
  smallTeam: "Small team",
  severalStakeholders: "Several stakeholders",
  leadership: "Leadership / board",
  multipleOrgs: "Multiple teams or organisations",
  agencyPartner: "Agency / external partner",
  notYet: "Not yet",
  under3000: "Under €3,000",
  "3000-5000": "€3,000–€5,000",
  "5000-10000": "€5,000–€10,000",
  "10000-20000": "€10,000–€20,000",
  "20000+": "€20,000+",
} as const;

export const en: ProjectFlowContent = {
  meta: {
    title: "Let’s talk about the project · UrsoParvo Studio",
    description:
      "Tell us what you are trying to solve. You do not need a brief. We come back with a reading of the project and the next steps.",
  },
  intro: {
    kicker: "Project",
    title: "Let’s talk about the project",
    body: "You do not need to know exactly what you need. Choose what feels closest.",
  },
  nav: {
    back: "Back",
    continue: "Continue",
    skip: "Not now",
    edit: "Edit",
    talk: "Let’s talk",
    send: "Send the summary",
    sending: "Sending…",
    startAgain: "Start again",
    stepStatus: "{current} of {total}",
  },
  questions: {
    projectType: {
      kicker: "Project",
      question: "What are you trying to solve?",
      description: "You do not need a brief. Choose what feels closest.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "identityRedesign",
          label: "The brand exists and needs to change visually",
          description: "There is a logo, an identity, or materials that no longer work.",
        },
        {
          id: "visualIdentity",
          label: "A new visual identity is needed",
          description: "For a brand that is emerging, or that does not yet have a clear face.",
        },
        {
          id: "visualDirection",
          label: "It is for an event, campaign or launch",
          description: "A specific moment needs a visual language.",
        },
        {
          id: "specificAsset",
          label: "It is a particular piece",
          description: "A poster, an illustration, a cover, a printed piece.",
        },
        {
          id: "unsure",
          label: "I’m not sure yet",
          description: "I know something needs to change. I don’t yet know what the project is.",
        },
      ],
    },
    existingBrand: {
      kicker: "What exists",
      question: "What does the brand already have?",
      description: "You can choose more than one. If you are not sure, that is fine.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "nameAndBusiness", label: "A name and a business" },
        { id: "logo", label: "A logo" },
        { id: "visualIdentity", label: "A visual identity" },
        { id: "disconnectedMaterials", label: "Several materials that don’t quite hold together" },
        { id: "unsure", label: "I’m not sure yet" },
      ],
    },
    redesignDepth: {
      kicker: "Scope",
      question: "How much needs to change?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "refine",
          label: "Refine what already exists",
          description: "The foundation is sound. It needs more clarity and consistency.",
        },
        {
          id: "reimagine",
          label: "Change it in a visible way",
          description: "The brand stays recognisable, but the look needs a clear shift.",
        },
        {
          id: "rebuild",
          label: "Rethink the visuals from the ground up",
          description: "What exists no longer represents the brand.",
        },
      ],
    },
    strategyClarity: {
      kicker: "Direction",
      question: "Is the idea of the brand already defined?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "veryClear",
          label: "Yes, it is clear",
          description: "We know who it is and where it is going.",
        },
        {
          id: "mostlyClear",
          label: "There is a direction, with things still to clarify",
        },
        {
          id: "stillTakingShape",
          label: "It is still taking shape",
        },
        {
          id: "unsure",
          label: "I need help understanding where to start",
        },
      ],
    },
    identityScope: {
      kicker: "Identity",
      question: "What needs to be part of this?",
      description: "Choose what is relevant. The rest can wait.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "logo", label: "Logo" },
        { id: "symbol", label: "Symbol" },
        { id: "typography", label: "Typography" },
        { id: "colour", label: "Colour" },
        { id: "graphicLanguage", label: "Graphic language" },
        { id: "illustration", label: "Illustration" },
        { id: "templates", label: "Templates for everyday use" },
        { id: "other", label: "Something else" },
      ],
    },
    systemDepth: {
      kicker: "Reach",
      question: "How far should the work go?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "foundations",
          label: "The essentials",
          description: "The visual foundations and how to use them correctly.",
        },
        {
          id: "system",
          label: "A system that works in different places",
          description: "A visual language meant to hold across contexts.",
        },
        {
          id: "systemAndApplications",
          label: "The system and its main applications",
          description: "The foundations, plus the pieces the brand actually appears on.",
        },
        {
          id: "completeSystem",
          label: "A complete system the team can keep using",
          description: "Meant to live beyond this project.",
        },
      ],
    },
    guidelines: {
      kicker: "Guidance",
      question: "How much guidance will the identity need?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "essential",
          label: labels.essential,
          description: "Core rules for correct use.",
        },
        {
          id: "standard",
          label: labels.standard,
          description: "Core rules plus system behaviour and applications.",
        },
        {
          id: "detailed",
          label: labels.detailed,
          description: "A comprehensive document designed to support continued internal use.",
        },
      ],
    },
    applications: {
      kicker: "Where it appears",
      question: "Where does this need to appear?",
      description: "Choose the places that matter now. It does not have to be exhaustive.",
      continueLabel: "Continue",
      backLabel: "Back",
      groups: [
        {
          id: "digital",
          label: "Digital",
          options: [
            { id: "website", label: "Website" },
            { id: "social", label: "Social media" },
            { id: "presentations", label: "Presentations" },
          ],
        },
        {
          id: "editorial",
          label: "Print",
          options: [
            { id: "print", label: "Printed material" },
            { id: "publications", label: "Publications" },
          ],
        },
        {
          id: "physical",
          label: "Physical",
          options: [
            { id: "packaging", label: "Packaging" },
            { id: "signage", label: "Signage" },
            { id: "environment", label: "Environment" },
            { id: "merchandise", label: "Merchandise" },
          ],
        },
        {
          id: "campaigns",
          label: "Campaign",
          options: [
            { id: "advertising", label: "Advertising" },
            { id: "posters", label: "Posters" },
            { id: "events", label: "Events" },
          ],
        },
      ],
    },
    applicationScale: {
      kicker: "Scale",
      question: "How extensive are the applications?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "few", label: labels.few },
        { id: "smallSet", label: labels.smallSet },
        { id: "broad", label: labels.broad },
        { id: "many", label: labels.many },
        { id: "unsure", label: "Not sure" },
      ],
    },
    campaignKind: {
      kicker: "Campaign",
      question: "What are we creating?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "eventIdentity", label: "The visual face of an event" },
        { id: "keyVisual", label: "A main image" },
        { id: "campaignLanguage", label: "A language for the campaign" },
        { id: "posterCampaign", label: "A poster campaign" },
        { id: "digitalCampaign", label: "A digital campaign" },
        { id: "fullCommunication", label: "A full communication system" },
        { id: "other", label: "Something else" },
      ],
    },
    campaignPlacements: {
      kicker: "Where it appears",
      question: "Where will this appear?",
      description: "You can choose more than one place.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "posters", label: "Posters" },
        { id: "social", label: "Social media" },
        { id: "website", label: "Website" },
        { id: "advertising", label: "Advertising" },
        { id: "signage", label: "Signage" },
        { id: "stage", label: "Stage / venue" },
        { id: "merchandise", label: "Merchandise" },
        { id: "editorial", label: "Print" },
        { id: "other", label: "Other" },
      ],
    },
    specificKind: {
      kicker: "Piece",
      question: "What kind of piece is this?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "illustration", label: "Illustration" },
        { id: "poster", label: "Poster" },
        { id: "editorial", label: "An image for a publication" },
        { id: "cover", label: "Cover" },
        { id: "packaging", label: "Packaging" },
        { id: "eventArtwork", label: "An image for an event" },
        { id: "printPiece", label: "Another printed piece" },
        { id: "other", label: "Something else" },
      ],
    },
    imageComplexity: {
      kicker: "Image",
      question: "How complex is the image?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "simple", label: labels.simple },
        { id: "developed", label: labels.developed },
        { id: "highlyDetailed", label: labels.highlyDetailed },
        { id: "unsure", label: "Not sure" },
      ],
    },
    pieceCount: {
      kicker: "Quantity",
      question: "How many final pieces?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "1", label: "One" },
        { id: "2-3", label: "Two or three" },
        { id: "4-6", label: "Four to six" },
        { id: "7+", label: "Seven or more" },
      ],
    },
    specialists: {
      kicker: "Around it",
      question: "Does the project need anything beyond the visual work?",
      description: "Only what is needed. If not, continue.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "motion",
          label: "Motion",
          description: "Animation, or the identity in movement.",
        },
        {
          id: "film",
          label: "Film",
          description: "Video, filming or editing.",
        },
        {
          id: "photography",
          label: "Photography",
        },
        {
          id: "digitalDesign",
          label: "Website",
          description: "The design of a page or a digital experience.",
        },
        {
          id: "development",
          label: "Development",
          description: "Making the site or digital piece work.",
        },
        {
          id: "3d",
          label: "3D",
        },
        {
          id: "writing",
          label: "Writing",
          description: "A name, words, a tone of voice.",
        },
        {
          id: "spatial",
          label: "Space",
          description: "Signage, or the brand in a physical place.",
        },
      ],
    },
    timeline: {
      kicker: "Timeline",
      question: "Is there a date in mind?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "noDate", label: "Not yet" },
        { id: "fewMonths", label: "In the coming months" },
        { id: "specificDate", label: "Yes, there is a specific date" },
        { id: "quickly", label: "We need to move quickly" },
      ],
    },
    targetDate: {
      kicker: "Timeline",
      question: "What is the date?",
      dateLabel: "When do you need this?",
      continueLabel: "Continue",
      backLabel: "Back",
    },
    stakeholders: {
      kicker: "People",
      question: "Who decides on this project?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "oneDecisionMaker", label: "One person" },
        { id: "smallTeam", label: "A small team" },
        { id: "severalStakeholders", label: "Several people deciding" },
        { id: "multipleOrgs", label: "Several teams or organisations" },
      ],
    },
    budget: {
      kicker: "Investment",
      question: "Do you already have a sense of scale?",
      helper: "It does not need to be exact. It helps us understand the scale.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "notYet", label: "Not yet" },
        { id: "under3000", label: labels.under3000 },
        { id: "3000-5000", label: labels["3000-5000"] },
        { id: "5000-10000", label: labels["5000-10000"] },
        { id: "10000-20000", label: labels["10000-20000"] },
        { id: "20000+", label: labels["20000+"] },
      ],
    },
    description: {
      kicker: "Context",
      question: "What is happening — and what would you like to be different?",
      placeholder: "Informal is fine. It does not need to be defined.",
      continueLabel: "Continue",
      backLabel: "Back",
    },
  },
  review: {
    kicker: "Reading",
    title: "Your project",
    empty: "Not specified",
    continueLabel: "Continue",
  },
  estimate: {
    kicker: "Reading",
    seeing: "This is what we are seeing.",
    initial: "Initial estimate",
    indicative: "Indicative estimate",
    lowTitle: "This project needs a conversation.",
    lowBody:
      "There is not yet enough to put a responsible number on it — and that is a fine place to start. The next step is to talk.",
    refinement:
      "It is based on what you described above. We will refine it when we talk through the project properly.",
    specialists:
      "It may make sense to bring in {list} if that becomes useful.",
    talk: "Let’s talk",
    edit: "Edit",
    preparing: "Preparing…",
    scale: {
      contained: "a contained scale",
      medium: "a medium scale",
      mediumLarge: "a medium-to-large scope",
      large: "a large scope",
    },
  },
  contact: {
    kicker: "Contact",
    question: "Where should we send the summary?",
    name: "Name",
    email: "Email",
    company: "Company / organisation",
    website: "Website",
    phone: "Phone",
    optional: "optional",
    nameError: "We need a name so we know who we are speaking with.",
    emailError: "We need an email address so we can send the project summary.",
  },
  complete: {
    kicker: "Sent",
    title: "We have the project.",
    body: "We’ll read it and reply with the next steps.",
    home: "Back to the start",
  },
  errors: {
    submit:
      "Something prevented the project from being submitted. Your answers are still here. Please try again.",
    estimate: "The estimate could not be prepared. Your answers are still here.",
    choose: "Choose one to continue.",
  },
  classifications: {
    identityRefresh: "a visual identity refinement",
    identityRedesign: "a visual identity redesign",
    identitySystem: "a visual identity system",
    visualIdentity: "a new visual identity",
    campaignEvent: "a visual direction for an event or campaign",
    keyVisual: "a main campaign image",
    specificGraphic: "a specific graphic piece",
    needsConversation: "a project still taking shape",
  },
  assumptions: {
    scopeDescribed: "The estimate assumes the scope described above.",
    estimateNotBinding:
      "This is an initial estimate, not a quotation. The proposal is confirmed after we discuss the project.",
    strategyPartiallyDefined: "The strategic direction appears partially defined.",
    strategyUndefined: "The direction is still taking shape.",
    specialistsIntegrated:
      "Specialist extensions can be brought into the project when they are useful.",
    discoveryRecommended: "A conversation is recommended before confirming scope and fees.",
    applicationsUncertain: "The extent of the applications is still unclear.",
    timelineFlexible: "There is no fixed date constraining the schedule.",
  },
  confidence: {
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  labels: {
    ...labels,
    visualIdentityExisting: "A visual identity",
    logoMark: "A logo",
    poster: "Poster",
    "pieces:1": "1 final piece",
    "pieces:2-3": "2–3 final pieces",
    "pieces:4-6": "4–6 final pieces",
    "pieces:7+": "7 or more final pieces",
  },
  brief: {
    project: "PROJECT",
    overview: "OVERVIEW",
    scope: "SCOPE",
    applications: "APPLICATIONS",
    extensions: "EXTENSIONS",
    timeline: "TIMELINE",
    budget: "BUDGET",
    initialEstimate: "INITIAL ESTIMATE",
    confidence: "CONFIDENCE",
    notes: "NOTES",
    contact: "CONTACT",
    none: "None",
    notSpecified: "Not specified",
    toBeDiscussed: "To be discussed",
    labels: {
      ...labels,
      visualIdentity: "Create a visual identity",
      logo: "Logo / wordmark",
      poster: "Poster",
      "pieces:1": "1 final piece",
      "pieces:2-3": "2–3 final pieces",
      "pieces:4-6": "4–6 final pieces",
      "pieces:7+": "7 or more final pieces",
      visualIdentityExisting: "A visual identity",
      logoMark: "A logo",
    },
    confidenceLabels: {
      high: "High",
      medium: "Medium",
      low: "Low",
    },
  },
  stepAria: {},
};
