import type { ProjectFlowContent } from "./types";

const labels = {
  identityRedesign: "Redesign an existing brand",
  visualIdentity: "Create a visual identity",
  visualDirection: "Create a visual direction",
  specificAsset: "Create something specific",
  unsure: "I’m not sure yet",
  nameAndBusiness: "A name and a business",
  logo: "Logo / wordmark",
  fullVisualSystem: "A full visual system",
  identityNoLongerWorks: "An identity that no longer works",
  disconnectedMaterials: "Several disconnected visual materials",
  refine: "Refine",
  reimagine: "Reimagine",
  rebuild: "Rebuild",
  veryClear: "Very clear",
  mostlyClear: "Mostly clear",
  stillTakingShape: "Still taking shape",
  symbol: "Symbol / mark",
  typography: "Typography",
  colour: "Colour system",
  graphicLanguage: "Graphic language",
  illustration: "Illustration",
  iconography: "Iconography",
  photographyDirection: "Photography direction",
  layoutSystem: "Layout / composition system",
  templates: "Templates",
  packaging: "Packaging",
  signage: "Signage",
  merchandise: "Merchandise",
  other: "Other",
  foundations: "Foundations",
  system: "System",
  systemAndApplications: "System and applications",
  completeSystem: "Complete system",
  essential: "Essential",
  standard: "Standard",
  detailed: "Detailed",
  website: "Website",
  social: "Social media",
  email: "Email",
  digitalProducts: "Digital products",
  presentations: "Presentations",
  reports: "Reports",
  brochures: "Brochures",
  publications: "Publications",
  print: "Printed material",
  environment: "Environment",
  objects: "Objects",
  advertising: "Advertising",
  posters: "Posters",
  launches: "Launches",
  events: "Events",
  few: "A few key applications",
  smallSet: "A small set",
  broad: "A broad range",
  many: "Many applications across different contexts",
  eventIdentity: "Event identity",
  keyVisual: "Key visual",
  campaignLanguage: "Campaign visual language",
  posterCampaign: "Poster / print campaign",
  digitalCampaign: "Digital campaign",
  fullCommunication: "Full communication system",
  stage: "Stage / venue",
  editorial: "Editorial",
  cover: "Album / cover artwork",
  eventArtwork: "Event artwork",
  printPiece: "Print piece",
  simple: "Simple",
  developed: "Developed",
  highlyDetailed: "Highly detailed",
  "1": "1",
  "2-3": "2–3",
  "4-6": "4–6",
  "7+": "7+",
  motion: "Motion",
  film: "Film",
  photography: "Photography",
  digitalDesign: "Digital",
  development: "Development",
  "3d": "3D",
  writing: "Writing",
  spatial: "Spatial",
  noDate: "No fixed date",
  fewMonths: "Within the next few months",
  specificDate: "I have a specific date",
  quickly: "We need to move quickly",
  oneDecisionMaker: "One decision-maker",
  smallTeam: "Small team",
  severalStakeholders: "Several stakeholders",
  leadership: "Leadership / board",
  multipleOrgs: "Multiple teams or organisations",
  agencyPartner: "Agency / external partner",
  notYet: "Not yet",
  under3000: "Under €3,000",
  "3000-5000": "€3,000–€5,000",
  "5000-10000": "€5,000–€10,000",
  "10000-20000": "€10,000–€20,000",
  "20000+": "€20,000+",
} as const;

export const en: ProjectFlowContent = {
  meta: {
    title: "Let’s talk about the project · UrsoParvo Studio",
    description:
      "Tell us what needs to change, be created or communicated. We’ll come back with a clear reading of the project and an initial estimate.",
  },
  intro: {
    kicker: "Project",
    title: "Let’s talk about the project",
    body: "A few questions so we can understand what is at stake. You don’t need to have everything defined.",
  },
  nav: {
    back: "Back",
    continue: "Continue",
    edit: "Edit",
    talk: "Talk about the project",
    send: "Send the summary",
    sending: "Sending…",
    startAgain: "Start again",
    stepStatus: "Step {current} of {total}",
  },
  questions: {
    projectType: {
      kicker: "Project",
      question: "What are we working on?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "identityRedesign",
          label: labels.identityRedesign,
          description: "The brand exists, but its visual identity needs to evolve.",
        },
        {
          id: "visualIdentity",
          label: labels.visualIdentity,
          description: "A new visual identity is needed for an existing or emerging brand.",
        },
        {
          id: "visualDirection",
          label: labels.visualDirection,
          description:
            "A campaign, event, festival, launch or specific communication needs a visual language.",
        },
        {
          id: "specificAsset",
          label: labels.specificAsset,
          description:
            "A particular graphic, illustration, poster, publication, object or visual asset.",
        },
        {
          id: "unsure",
          label: labels.unsure,
          description: "I know something needs to change, but I am not sure what the project should be.",
        },
      ],
    },
    existingBrand: {
      kicker: "What exists",
      question: "What already exists?",
      description: "You can choose more than one answer.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "nameAndBusiness", label: labels.nameAndBusiness },
        { id: "logo", label: "A logo" },
        { id: "visualIdentity", label: "A visual identity" },
        { id: "fullVisualSystem", label: labels.fullVisualSystem },
        { id: "identityNoLongerWorks", label: labels.identityNoLongerWorks },
        { id: "disconnectedMaterials", label: labels.disconnectedMaterials },
        { id: "unsure", label: "Not sure" },
      ],
    },
    redesignDepth: {
      kicker: "Scope",
      question: "How much needs to change?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "refine",
          label: labels.refine,
          description:
            "The existing identity has a strong foundation. It needs clarity, consistency or refinement.",
        },
        {
          id: "reimagine",
          label: labels.reimagine,
          description:
            "The brand is still recognisable, but its visual expression needs a significant change.",
        },
        {
          id: "rebuild",
          label: labels.rebuild,
          description:
            "The existing identity no longer reflects the brand and needs to be substantially rethought visually.",
        },
      ],
    },
    strategyClarity: {
      kicker: "Direction",
      question: "How clear is the direction already?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "veryClear",
          label: labels.veryClear,
          description: "The positioning and direction are already defined.",
        },
        {
          id: "mostlyClear",
          label: labels.mostlyClear,
          description: "There is a direction, but some things still need to be clarified.",
        },
        {
          id: "stillTakingShape",
          label: labels.stillTakingShape,
          description: "The brand itself is still being defined.",
        },
        {
          id: "unsure",
          label: "Not sure",
          description: "I need help understanding where to start.",
        },
      ],
    },
    identityScope: {
      kicker: "Identity",
      question: "What needs to be part of the identity?",
      description: "Choose what is relevant. This is not a shopping list.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "logo", label: labels.logo },
        { id: "symbol", label: labels.symbol },
        { id: "typography", label: labels.typography },
        { id: "colour", label: labels.colour },
        { id: "graphicLanguage", label: labels.graphicLanguage },
        { id: "illustration", label: labels.illustration },
        { id: "iconography", label: labels.iconography },
        { id: "photographyDirection", label: labels.photographyDirection },
        { id: "layoutSystem", label: labels.layoutSystem },
        { id: "templates", label: labels.templates },
        { id: "packaging", label: labels.packaging },
        { id: "signage", label: labels.signage },
        { id: "merchandise", label: labels.merchandise },
        { id: "other", label: labels.other },
      ],
    },
    systemDepth: {
      kicker: "System",
      question: "How far should the visual system go?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "foundations",
          label: labels.foundations,
          description: "Core visual elements and rules.",
        },
        {
          id: "system",
          label: labels.system,
          description: "A flexible visual language designed to work across different contexts.",
        },
        {
          id: "systemAndApplications",
          label: labels.systemAndApplications,
          description: "The visual system plus its main real-world applications.",
        },
        {
          id: "completeSystem",
          label: labels.completeSystem,
          description:
            "A robust identity system designed for continued use by a wider team.",
        },
      ],
    },
    guidelines: {
      kicker: "Guidance",
      question: "How much guidance will the identity need?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "essential",
          label: labels.essential,
          description: "Core rules for correct use.",
        },
        {
          id: "standard",
          label: labels.standard,
          description: "Core rules plus system behaviour and applications.",
        },
        {
          id: "detailed",
          label: labels.detailed,
          description: "A comprehensive document designed to support continued internal use.",
        },
      ],
    },
    applications: {
      kicker: "Contexts",
      question: "Where will the identity need to work?",
      continueLabel: "Continue",
      backLabel: "Back",
      groups: [
        {
          id: "digital",
          label: "Digital",
          options: [
            { id: "website", label: labels.website },
            { id: "social", label: labels.social },
            { id: "email", label: labels.email },
            { id: "digitalProducts", label: labels.digitalProducts },
            { id: "presentations", label: labels.presentations },
          ],
        },
        {
          id: "editorial",
          label: "Editorial",
          options: [
            { id: "reports", label: labels.reports },
            { id: "brochures", label: labels.brochures },
            { id: "publications", label: labels.publications },
            { id: "print", label: labels.print },
          ],
        },
        {
          id: "physical",
          label: "Physical",
          options: [
            { id: "packaging", label: labels.packaging },
            { id: "signage", label: labels.signage },
            { id: "environment", label: labels.environment },
            { id: "merchandise", label: labels.merchandise },
            { id: "objects", label: labels.objects },
          ],
        },
        {
          id: "campaigns",
          label: "Campaigns",
          options: [
            { id: "advertising", label: labels.advertising },
            { id: "posters", label: labels.posters },
            { id: "launches", label: labels.launches },
            { id: "events", label: labels.events },
          ],
        },
      ],
    },
    applicationScale: {
      kicker: "Scale",
      question: "How extensive are the applications?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "few", label: labels.few },
        { id: "smallSet", label: labels.smallSet },
        { id: "broad", label: labels.broad },
        { id: "many", label: labels.many },
        { id: "unsure", label: "Not sure" },
      ],
    },
    campaignKind: {
      kicker: "Campaign",
      question: "What are we creating?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "eventIdentity", label: labels.eventIdentity },
        { id: "keyVisual", label: labels.keyVisual },
        { id: "campaignLanguage", label: labels.campaignLanguage },
        { id: "posterCampaign", label: labels.posterCampaign },
        { id: "digitalCampaign", label: labels.digitalCampaign },
        { id: "fullCommunication", label: labels.fullCommunication },
        { id: "other", label: labels.other },
      ],
    },
    campaignPlacements: {
      kicker: "Contexts",
      question: "Where will it live?",
      description: "You can choose more than one context.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "posters", label: labels.posters },
        { id: "social", label: labels.social },
        { id: "website", label: labels.website },
        { id: "advertising", label: labels.advertising },
        { id: "signage", label: labels.signage },
        { id: "stage", label: labels.stage },
        { id: "merchandise", label: labels.merchandise },
        { id: "editorial", label: labels.editorial },
        { id: "other", label: labels.other },
      ],
    },
    specificKind: {
      kicker: "Piece",
      question: "What are we making?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "illustration", label: labels.illustration },
        { id: "poster", label: "Poster" },
        { id: "editorial", label: "Editorial artwork" },
        { id: "cover", label: labels.cover },
        { id: "packaging", label: "Packaging artwork" },
        { id: "eventArtwork", label: labels.eventArtwork },
        { id: "printPiece", label: labels.printPiece },
        { id: "other", label: labels.other },
      ],
    },
    imageComplexity: {
      kicker: "Image",
      question: "How complex is the image?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "simple", label: labels.simple },
        { id: "developed", label: labels.developed },
        { id: "highlyDetailed", label: labels.highlyDetailed },
        { id: "unsure", label: "Not sure" },
      ],
    },
    pieceCount: {
      kicker: "Quantity",
      question: "How many final pieces?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "1", label: "1" },
        { id: "2-3", label: "2–3" },
        { id: "4-6", label: "4–6" },
        { id: "7+", label: "7+" },
      ],
    },
    specialists: {
      kicker: "Extensions",
      question: "Could the project extend beyond visual design?",
      description:
        "These are not extras. They are possible requirements, if they belong in the project.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        {
          id: "motion",
          label: labels.motion,
          description: "Animation, motion identity or animated assets.",
        },
        {
          id: "film",
          label: labels.film,
          description: "Video, filming, editing or audiovisual campaigns.",
        },
        {
          id: "photography",
          label: labels.photography,
          description: "Photography production or art direction.",
        },
        {
          id: "digitalDesign",
          label: labels.digitalDesign,
          description: "Website design, landing pages or digital experiences.",
        },
        {
          id: "development",
          label: labels.development,
          description: "Web development or technical implementation.",
        },
        {
          id: "advertising",
          label: labels.advertising,
          description: "Campaign development and advertising assets.",
        },
        {
          id: "3d",
          label: labels["3d"],
          description: "3D imagery, renders or animation.",
        },
        {
          id: "writing",
          label: labels.writing,
          description: "Naming, copywriting or verbal identity.",
        },
        {
          id: "spatial",
          label: labels.spatial,
          description: "Environmental graphics, signage or physical experiences.",
        },
      ],
    },
    timeline: {
      kicker: "Timeline",
      question: "Is there a date we need to work towards?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "noDate", label: labels.noDate },
        { id: "fewMonths", label: labels.fewMonths },
        { id: "specificDate", label: labels.specificDate },
        { id: "quickly", label: labels.quickly },
      ],
    },
    targetDate: {
      kicker: "Timeline",
      question: "What is the date?",
      dateLabel: "Date",
      continueLabel: "Continue",
      backLabel: "Back",
    },
    stakeholders: {
      kicker: "Process",
      question: "Who will be involved in the process?",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "oneDecisionMaker", label: labels.oneDecisionMaker },
        { id: "smallTeam", label: labels.smallTeam },
        { id: "severalStakeholders", label: labels.severalStakeholders },
        { id: "leadership", label: labels.leadership },
        { id: "multipleOrgs", label: labels.multipleOrgs },
        { id: "agencyPartner", label: labels.agencyPartner },
      ],
    },
    budget: {
      kicker: "Investment",
      question: "Do you already have an investment range in mind?",
      helper: "It doesn’t need to be exact. It simply helps us understand the scale you’re considering.",
      continueLabel: "Continue",
      backLabel: "Back",
      options: [
        { id: "notYet", label: labels.notYet },
        { id: "under3000", label: labels.under3000 },
        { id: "3000-5000", label: labels["3000-5000"] },
        { id: "5000-10000", label: labels["5000-10000"] },
        { id: "10000-20000", label: labels["10000-20000"] },
        { id: "20000+", label: labels["20000+"] },
      ],
    },
    description: {
      kicker: "Context",
      question: "Tell us a little about the project.",
      placeholder: "What are you trying to change, create or communicate?",
      continueLabel: "Continue",
      backLabel: "Back",
    },
  },
  review: {
    kicker: "Reading",
    title: "Your project",
    empty: "Not specified",
    continueLabel: "Continue",
  },
  estimate: {
    kicker: "Reading",
    seeing: "This is what we’re seeing.",
    initial: "Initial estimate",
    indicative: "Indicative estimate",
    lowTitle: "This project needs a conversation.",
    lowBody:
      "We don’t have enough information to estimate it responsibly yet. The next step is to talk.",
    refinement:
      "This estimate is based on the scope described above. We can refine it once we understand the project in more detail.",
    specialists:
      "The project may also involve specialist collaborators in {list}. These can be integrated into the project when useful.",
    talk: "Talk about the project",
    edit: "Edit project",
    scale: {
      contained: "a contained scale",
      medium: "a medium scale",
      mediumLarge: "a medium-to-large scope",
      large: "a large scope",
    },
  },
  contact: {
    kicker: "Contact",
    question: "Where should we send the project summary?",
    name: "Name",
    email: "Email",
    company: "Company / organisation",
    website: "Website",
    phone: "Phone",
    optional: "optional",
    nameError: "Please add a name so we know who we are speaking with.",
    emailError: "Please add an email address so we know where to send the project summary.",
  },
  complete: {
    kicker: "Sent",
    title: "We have the project.",
    body: "We’ll read what you sent and reply to the email you gave us.",
    home: "Back to the start",
  },
  errors: {
    submit:
      "Something prevented the project from being submitted. Your answers are still here. Please try again.",
    estimate: "The estimate could not be prepared. Your answers are still here.",
  },
  classifications: {
    identityRefresh: "a visual identity refinement",
    identityRedesign: "a visual identity redesign",
    identitySystem: "a visual identity system",
    visualIdentity: "a new visual identity",
    campaignEvent: "a visual direction for an event or campaign",
    keyVisual: "a key visual",
    specificGraphic: "a specific graphic piece",
    needsConversation: "a project still taking shape",
  },
  assumptions: {
    scopeDescribed: "The estimate assumes the scope described above.",
    estimateNotBinding:
      "This is an initial estimate, not a quotation. The proposal is confirmed after we discuss the project.",
    strategyPartiallyDefined: "The strategic direction appears partially defined.",
    strategyUndefined: "The direction is still taking shape.",
    specialistsIntegrated:
      "Specialist extensions can be brought into the project when they are useful.",
    discoveryRecommended: "A conversation is recommended before confirming scope and fees.",
    applicationsUncertain: "The extent of the applications is still unclear.",
    timelineFlexible: "There is no fixed date constraining the schedule.",
  },
  confidence: {
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  labels: {
    ...labels,
    visualIdentityExisting: "A visual identity",
    logoMark: "A logo",
    poster: "Poster",
    "pieces:1": "1 final piece",
    "pieces:2-3": "2–3 final pieces",
    "pieces:4-6": "4–6 final pieces",
    "pieces:7+": "7 or more final pieces",
  },
  brief: {
    project: "PROJECT",
    overview: "OVERVIEW",
    scope: "SCOPE",
    applications: "APPLICATIONS",
    extensions: "EXTENSIONS",
    timeline: "TIMELINE",
    budget: "BUDGET",
    initialEstimate: "INITIAL ESTIMATE",
    confidence: "CONFIDENCE",
    notes: "NOTES",
    contact: "CONTACT",
    none: "None",
    notSpecified: "Not specified",
    toBeDiscussed: "To be discussed",
    labels: {
      ...labels,
      visualIdentity: "Create a visual identity",
      logo: "Logo / wordmark",
      poster: "Poster",
      "pieces:1": "1 final piece",
      "pieces:2-3": "2–3 final pieces",
      "pieces:4-6": "4–6 final pieces",
      "pieces:7+": "7 or more final pieces",
      visualIdentityExisting: "A visual identity",
      logoMark: "A logo",
    },
    confidenceLabels: {
      high: "High",
      medium: "Medium",
      low: "Low",
    },
  },
  stepAria: {},
};
