import type { ProjectFlowContent } from "./types";

const labels = {
  identityRedesign: "Redesenhar uma marca existente",
  visualIdentity: "Criar uma identidade visual",
  visualDirection: "Criar uma direcção visual",
  specificAsset: "Criar algo específico",
  unsure: "Ainda não sei",
  nameAndBusiness: "Um nome e uma actividade",
  logo: "Logótipo / wordmark",
  visualIdentityState: "Uma identidade visual",
  fullVisualSystem: "Um sistema visual completo",
  identityNoLongerWorks: "Uma identidade que já não funciona",
  disconnectedMaterials: "Materiais visuais desligados entre si",
  refine: "Afinar",
  reimagine: "Reimaginar",
  rebuild: "Reconstruir",
  veryClear: "Muito clara",
  mostlyClear: "Em grande parte clara",
  stillTakingShape: "Ainda a tomar forma",
  symbol: "Símbolo / marca",
  typography: "Tipografia",
  colour: "Sistema de cor",
  graphicLanguage: "Linguagem gráfica",
  illustration: "Ilustração",
  iconography: "Iconografia",
  photographyDirection: "Direcção fotográfica",
  layoutSystem: "Sistema de composição",
  templates: "Modelos",
  packaging: "Embalagem",
  signage: "Sinalética",
  merchandise: "Merchandising",
  other: "Outro",
  foundations: "Fundamentos",
  system: "Sistema",
  systemAndApplications: "Sistema + aplicações",
  completeSystem: "Sistema completo",
  essential: "Essencial",
  standard: "Padrão",
  detailed: "Detalhado",
  website: "Website",
  social: "Redes sociais",
  email: "Email",
  digitalProducts: "Produtos digitais",
  presentations: "Apresentações",
  reports: "Relatórios",
  brochures: "Brochuras",
  publications: "Publicações",
  print: "Material impresso",
  environment: "Espaço",
  objects: "Objectos",
  advertising: "Publicidade",
  posters: "Cartazes",
  launches: "Lançamentos",
  events: "Eventos",
  few: "Algumas aplicações-chave",
  smallSet: "Um conjunto pequeno",
  broad: "Um leque alargado",
  many: "Muitas aplicações, em contextos diferentes",
  eventIdentity: "Identidade de evento",
  keyVisual: "Key visual",
  campaignLanguage: "Linguagem visual de campanha",
  posterCampaign: "Campanha de cartaz / impressão",
  digitalCampaign: "Campanha digital",
  fullCommunication: "Sistema de comunicação completo",
  stage: "Palco / recinto",
  editorial: "Editorial",
  cover: "Capa / artwork de álbum",
  eventArtwork: "Artwork de evento",
  printPiece: "Peça impressa",
  simple: "Simples",
  developed: "Desenvolvida",
  highlyDetailed: "Muito detalhada",
  "1": "1",
  "2-3": "2–3",
  "4-6": "4–6",
  "7+": "7 ou mais",
  motion: "motion",
  film: "vídeo",
  photography: "fotografia",
  digitalDesign: "digital",
  development: "desenvolvimento",
  "3d": "3D",
  writing: "texto",
  spatial: "espaço",
  noDate: "Sem data fixa",
  fewMonths: "Nos próximos meses",
  specificDate: "Tenho uma data concreta",
  quickly: "Precisamos de avançar depressa",
  oneDecisionMaker: "Uma pessoa a decidir",
  smallTeam: "Uma equipa pequena",
  severalStakeholders: "Várias pessoas envolvidas",
  leadership: "Direcção / conselho",
  multipleOrgs: "Várias equipas ou organizações",
  agencyPartner: "Agência / parceiro externo",
  notYet: "Ainda não",
  under3000: "Menos de 3 000 €",
  "3000-5000": "3 000–5 000 €",
  "5000-10000": "5 000–10 000 €",
  "10000-20000": "10 000–20 000 €",
  "20000+": "Mais de 20 000 €",
} as const;

export const pt: ProjectFlowContent = {
  meta: {
    title: "Falar sobre um projecto · UrsoParvo Studio",
    description:
      "Conte-nos sobre o projecto. Algumas perguntas ajudam-nos a perceber o que precisa de ser feito e a dar-lhe uma primeira estimativa.",
  },
  intro: {
    kicker: "Projecto",
    title: "Falar sobre um projecto",
    body: "Algumas perguntas ajudam-nos a perceber o que precisa de ser feito e a dar-lhe uma primeira estimativa.",
  },
  nav: {
    back: "Voltar",
    continue: "Continuar",
    skip: "Agora não",
    edit: "Editar",
    talk: "Falar sobre o projecto",
    send: "Enviar o resumo",
    sending: "A enviar…",
    startAgain: "Começar de novo",
    stepStatus: "{current} de {total}",
  },
  questions: {
    projectType: {
      kicker: "Projecto",
      question: "O que precisa de fazer?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "identityRedesign",
          label: "Redesenhar uma marca",
          description: "A marca existe, mas a identidade precisa de mudar.",
        },
        {
          id: "visualIdentity",
          label: "Criar uma identidade visual",
          description: "A marca precisa de uma identidade visual.",
        },
        {
          id: "visualDirection",
          label: "Criar uma imagem",
          description: "Uma campanha, evento, festival ou projecto precisa de uma linguagem visual.",
        },
        {
          id: "specificAsset",
          label: "Criar algo específico",
          description: "Uma ilustração, cartaz, publicação ou outra peça.",
        },
        {
          id: "unsure",
          label: "Ainda não sei",
          description: "Sei que alguma coisa precisa de mudar, mas ainda não sei exactamente o quê.",
        },
      ],
    },
    existingBrand: {
      kicker: "O que existe",
      question: "O que é que a marca já tem?",
      description: "Pode escolher mais do que uma. Se não tiver a certeza, não faz mal.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "nameAndBusiness", label: "Um nome e uma actividade" },
        { id: "logo", label: "Um logótipo" },
        { id: "visualIdentity", label: "Uma identidade visual" },
        { id: "disconnectedMaterials", label: "Vários materiais, pouco consistentes entre si" },
        { id: "unsure", label: "Ainda não tenho a certeza" },
      ],
    },
    redesignDepth: {
      kicker: "Âmbito",
      question: "O que precisa de mudar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "refine",
          label: "Afinar",
          description: "A base funciona, mas precisa de ser ajustada.",
        },
        {
          id: "reimagine",
          label: "Reimaginar",
          description: "A marca precisa de uma mudança visual significativa.",
        },
        {
          id: "rebuild",
          label: "Reconstruir",
          description: "A identidade já não corresponde ao que a marca é hoje.",
        },
      ],
    },
    strategyClarity: {
      kicker: "Direcção",
      question: "A marca já tem uma direcção definida?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "veryClear",
          label: "Sim",
        },
        {
          id: "mostlyClear",
          label: "Em grande parte",
        },
        {
          id: "stillTakingShape",
          label: "Ainda estamos a defini-la",
        },
        {
          id: "unsure",
          label: "Não sabemos por onde começar",
        },
      ],
    },
    identityScope: {
      kicker: "Identidade",
      question: "O que precisa de ser criado?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "logo", label: "Logótipo" },
        { id: "symbol", label: "Símbolo" },
        { id: "typography", label: "Tipografia" },
        { id: "colour", label: "Cor" },
        { id: "graphicLanguage", label: "Sistema gráfico" },
        { id: "illustration", label: "Ilustração" },
        { id: "iconography", label: "Iconografia" },
        { id: "photographyDirection", label: "Direcção fotográfica" },
        { id: "templates", label: "Templates" },
        { id: "packaging", label: "Packaging" },
        { id: "signage", label: "Sinalética" },
        { id: "merchandise", label: "Merchandising" },
        { id: "other", label: "Outra coisa" },
      ],
    },
    systemDepth: {
      kicker: "Alcance",
      question: "Até onde deve ir a identidade?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "foundations",
          label: "Fundamentos",
          description: "Os elementos essenciais da identidade.",
        },
        {
          id: "system",
          label: "Sistema",
          description: "Uma linguagem visual que funciona em diferentes contextos.",
        },
        {
          id: "systemAndApplications",
          label: "Sistema + aplicações",
          description: "A identidade e as principais aplicações.",
        },
        {
          id: "completeSystem",
          label: "Sistema completo",
          description: "Um sistema preparado para utilização continuada por uma equipa.",
        },
      ],
    },
    guidelines: {
      kicker: "Documentação",
      question: "Que documentação precisa?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "essential",
          label: labels.essential,
          description: "As regras necessárias para utilizar a identidade correctamente.",
        },
        {
          id: "standard",
          label: labels.standard,
          description: "Regras, sistema visual e aplicações.",
        },
        {
          id: "detailed",
          label: "Detalhada",
          description: "Documentação mais completa para utilização continuada.",
        },
      ],
    },
    applications: {
      kicker: "Onde aparece",
      question: "Onde vai aparecer?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      groups: [
        {
          id: "digital",
          label: "Digital",
          options: [
            { id: "website", label: "Website" },
            { id: "social", label: "Redes sociais" },
            { id: "email", label: "Email" },
            { id: "presentations", label: "Apresentações" },
          ],
        },
        {
          id: "editorial",
          label: "Impresso",
          options: [
            { id: "posters", label: "Cartazes" },
            { id: "brochures", label: "Brochuras" },
            { id: "publications", label: "Publicações" },
            { id: "packaging", label: "Packaging" },
          ],
        },
        {
          id: "physical",
          label: "Físico",
          options: [
            { id: "signage", label: "Sinalética" },
            { id: "environment", label: "Espaços" },
            { id: "merchandise", label: "Merchandising" },
            { id: "objects", label: "Objectos" },
          ],
        },
        {
          id: "campaigns",
          label: "Campanhas",
          options: [
            { id: "advertising", label: "Publicidade" },
            { id: "events", label: "Eventos" },
            { id: "launches", label: "Lançamentos" },
          ],
        },
      ],
    },
    applicationScale: {
      kicker: "Escala",
      question: "Quão extensas são as aplicações?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "few", label: labels.few },
        { id: "smallSet", label: labels.smallSet },
        { id: "broad", label: labels.broad },
        { id: "many", label: labels.many },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    campaignKind: {
      kicker: "Campanha",
      question: "O que estamos a criar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "eventIdentity", label: "A cara visual de um evento" },
        { id: "keyVisual", label: "Uma imagem principal" },
        { id: "campaignLanguage", label: "Uma linguagem para a campanha" },
        { id: "posterCampaign", label: "Uma campanha de cartaz" },
        { id: "digitalCampaign", label: "Uma campanha digital" },
        { id: "fullCommunication", label: "Um sistema de comunicação completo" },
        { id: "other", label: "Outra coisa" },
      ],
    },
    campaignPlacements: {
      kicker: "Onde aparece",
      question: "Onde é que isto vai aparecer?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "posters", label: "Cartazes" },
        { id: "social", label: "Redes sociais" },
        { id: "website", label: "Website" },
        { id: "advertising", label: "Publicidade" },
        { id: "signage", label: "Sinalética" },
        { id: "stage", label: "Palco / recinto" },
        { id: "merchandise", label: "Merchandising" },
        { id: "editorial", label: "Impresso" },
        { id: "other", label: "Outro" },
      ],
    },
    specificKind: {
      kicker: "Peça",
      question: "Que peça é esta?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "illustration", label: "Ilustração" },
        { id: "poster", label: "Cartaz" },
        { id: "editorial", label: "Imagem para uma publicação" },
        { id: "cover", label: "Capa" },
        { id: "packaging", label: "Embalagem" },
        { id: "eventArtwork", label: "Imagem para um evento" },
        { id: "printPiece", label: "Outro impresso" },
        { id: "other", label: "Outra coisa" },
      ],
    },
    imageComplexity: {
      kicker: "Imagem",
      question: "Quão complexa é a imagem?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "simple", label: labels.simple },
        { id: "developed", label: labels.developed },
        { id: "highlyDetailed", label: labels.highlyDetailed },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    pieceCount: {
      kicker: "Quantidade",
      question: "Quantas peças finais?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "1", label: "Uma" },
        { id: "2-3", label: "Duas ou três" },
        { id: "4-6", label: "Quatro a seis" },
        { id: "7+", label: "Sete ou mais" },
      ],
    },
    specialists: {
      kicker: "À volta",
      question: "O projecto precisa de mais alguma coisa?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "motion",
          label: "Motion",
          description: "Animação e movimento.",
        },
        {
          id: "film",
          label: "Vídeo",
          description: "Filmagem, edição ou produção audiovisual.",
        },
        {
          id: "photography",
          label: "Fotografia",
          description: "Fotografia ou direcção de imagem.",
        },
        {
          id: "digitalDesign",
          label: "Digital",
          description: "Website ou experiência digital.",
        },
        {
          id: "development",
          label: "Desenvolvimento",
          description: "Implementação técnica.",
        },
        {
          id: "advertising",
          label: "Publicidade",
          description: "Campanhas e peças de comunicação.",
        },
        {
          id: "3d",
          label: "3D",
          description: "Imagem ou animação 3D.",
        },
        {
          id: "writing",
          label: "Texto",
          description: "Naming, copy ou identidade verbal.",
        },
        {
          id: "spatial",
          label: "Espaço",
          description: "Sinalética ou comunicação no espaço.",
        },
      ],
    },
    timeline: {
      kicker: "Calendário",
      question: "Há uma data que precisamos de respeitar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "noDate", label: "Não" },
        { id: "fewMonths", label: "Nos próximos meses" },
        { id: "specificDate", label: "Tenho uma data definida" },
        { id: "quickly", label: "Precisamos de começar rapidamente" },
      ],
    },
    targetDate: {
      kicker: "Calendário",
      question: "Qual é a data?",
      dateLabel: "Quando precisa disto?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
    },
    stakeholders: {
      kicker: "Pessoas",
      question: "Quem vai participar nas decisões?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "oneDecisionMaker", label: "Uma pessoa" },
        { id: "smallTeam", label: "Uma pequena equipa" },
        { id: "severalStakeholders", label: "Várias pessoas" },
        { id: "leadership", label: "Direcção" },
        { id: "multipleOrgs", label: "Várias equipas ou organizações" },
        { id: "agencyPartner", label: "Agência / parceiro externo" },
      ],
    },
    budget: {
      kicker: "Orçamento",
      question: "Já tem um orçamento previsto?",
      helper: "Não precisa de ser exacto.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "notYet", label: "Ainda não" },
        { id: "under3000", label: labels.under3000 },
        { id: "3000-5000", label: labels["3000-5000"] },
        { id: "5000-10000", label: labels["5000-10000"] },
        { id: "10000-20000", label: labels["10000-20000"] },
        { id: "20000+", label: labels["20000+"] },
      ],
    },
    description: {
      kicker: "Contexto",
      question: "Conte-nos um pouco sobre o projecto.",
      placeholder: "O que está a tentar mudar, criar ou comunicar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
    },
  },
  review: {
    kicker: "Leitura",
    title: "O seu projecto",
    empty: "Por definir",
    continueLabel: "Continuar",
    sections: {
      type: "Tipo",
      scope: "Âmbito",
      applications: "Aplicações",
      extensions: "Extensões",
      timeline: "Calendário",
      budget: "Orçamento",
    },
  },
  estimate: {
    kicker: "Projecto",
    seeing: "O seu projecto",
    initial: "Estimativa inicial",
    indicative: "Estimativa inicial",
    lowTitle: "Ainda é cedo para dar uma estimativa.",
    lowBody:
      "Precisamos de perceber melhor o projecto antes de lhe dar um valor útil.",
    rangeNote:
      "Com base no que descreveu, este é o intervalo que estamos a considerar para o projecto.",
    finalNote:
      "O valor final será definido depois de percebermos o projecto em mais detalhe.",
    specialists:
      "Este projecto pode precisar de {list}. Se for o caso, trabalhamos com especialistas nessas áreas.",
    talk: "Falar sobre o projecto",
    edit: "Editar",
    preparing: "A preparar…",
    scale: {
      contained: "escala contida",
      medium: "escala média",
      mediumLarge: "âmbito médio a largo",
      large: "âmbito largo",
    },
  },
  contact: {
    kicker: "Contacto",
    question: "Onde podemos enviar o resumo?",
    name: "Nome",
    email: "Email",
    company: "Empresa / organização",
    website: "Website",
    phone: "Telefone",
    optional: "opcional",
    nameError: "Precisamos de um nome para sabermos com quem estamos a falar.",
    emailError: "Precisamos de um email para enviar o resumo do projecto.",
  },
  complete: {
    kicker: "Enviado",
    title: "Recebemos o projecto.",
    body: "Vamos lê-lo e responder com os próximos passos.",
    home: "Voltar ao início",
  },
  errors: {
    submit:
      "Algo impediu o envio do projecto. As respostas continuam aqui. Tente de novo.",
    estimate: "Não foi possível preparar a estimativa. As respostas continuam aqui.",
    choose: "Escolha uma opção para continuar.",
  },
  classifications: {
    identityRefresh: "um afinamento da identidade visual",
    identityRedesign: "um redesign de identidade visual",
    identitySystem: "um sistema de identidade visual",
    visualIdentity: "uma identidade visual nova",
    campaignEvent: "uma direcção visual para evento ou campanha",
    keyVisual: "uma imagem principal para campanha",
    specificGraphic: "uma peça gráfica específica",
    needsConversation: "um projecto ainda a definir",
  },
  assumptions: {
    scopeDescribed: "A estimativa parte do âmbito descrito acima.",
    estimateNotBinding:
      "É uma estimativa inicial, não uma cotação. A proposta fecha-se depois de falarmos do projecto.",
    strategyPartiallyDefined: "A direcção parece parcialmente definida.",
    strategyUndefined: "A direcção ainda está a tomar forma.",
    specialistsIntegrated:
      "Há extensões especializadas que podem entrar no projecto quando forem úteis.",
    discoveryRecommended: "Convém uma conversa antes de fechar âmbito e valores.",
    applicationsUncertain: "A extensão das aplicações ainda não está clara.",
    timelineFlexible: "Não há uma data fixa a condicionar o calendário.",
  },
  confidence: {
    high: "Alta",
    medium: "Média",
    low: "Baixa",
  },
  labels: {
    ...labels,
    visualIdentityExisting: "Uma identidade visual",
    logoMark: "Um logótipo",
    poster: "Cartaz",
    "pieces:1": "1 peça final",
    "pieces:2-3": "2–3 peças finais",
    "pieces:4-6": "4–6 peças finais",
    "pieces:7+": "7 ou mais peças finais",
  },
  brief: {
    project: "PROJECTO",
    overview: "ENQUADRAMENTO",
    scope: "ÂMBITO",
    applications: "APLICAÇÕES",
    extensions: "EXTENSÕES",
    timeline: "CALENDÁRIO",
    budget: "ORÇAMENTO",
    initialEstimate: "ESTIMATIVA INICIAL",
    confidence: "CONFIANÇA",
    notes: "NOTAS",
    contact: "CONTACTO",
    none: "Nenhuma",
    notSpecified: "Por definir",
    toBeDiscussed: "A discutir",
    labels: {
      ...labels,
      visualIdentity: "Criar uma identidade visual",
      logo: "Logótipo / wordmark",
      poster: "Cartaz",
      "pieces:1": "1 peça final",
      "pieces:2-3": "2–3 peças finais",
      "pieces:4-6": "4–6 peças finais",
      "pieces:7+": "7 ou mais peças finais",
      visualIdentityExisting: "Uma identidade visual",
      logoMark: "Um logótipo",
    },
    confidenceLabels: {
      high: "Alta",
      medium: "Média",
      low: "Baixa",
    },
  },
  stepAria: {},
};
