import type { ProjectFlowContent } from "./types";

const labels = {
  identityRedesign: "Redesenhar uma marca existente",
  visualIdentity: "Criar uma identidade visual",
  visualDirection: "Criar uma direcção visual",
  specificAsset: "Criar algo específico",
  unsure: "Ainda não sei",
  nameAndBusiness: "Um nome e uma actividade",
  logo: "Logótipo / wordmark",
  visualIdentityState: "Uma identidade visual",
  fullVisualSystem: "Um sistema visual completo",
  identityNoLongerWorks: "Uma identidade que já não funciona",
  disconnectedMaterials: "Materiais visuais desligados entre si",
  refine: "Afinar",
  reimagine: "Reimaginar",
  rebuild: "Reconstruir",
  veryClear: "Muito clara",
  mostlyClear: "Em grande parte clara",
  stillTakingShape: "Ainda a tomar forma",
  symbol: "Símbolo / marca",
  typography: "Tipografia",
  colour: "Sistema de cor",
  graphicLanguage: "Linguagem gráfica",
  illustration: "Ilustração",
  iconography: "Iconografia",
  photographyDirection: "Direcção fotográfica",
  layoutSystem: "Sistema de composição",
  templates: "Modelos",
  packaging: "Embalagem",
  signage: "Sinalética",
  merchandise: "Merchandising",
  other: "Outro",
  foundations: "Fundações",
  system: "Sistema",
  systemAndApplications: "Sistema e aplicações",
  completeSystem: "Sistema completo",
  essential: "Essencial",
  standard: "Padrão",
  detailed: "Detalhado",
  website: "Website",
  social: "Redes sociais",
  email: "Email",
  digitalProducts: "Produtos digitais",
  presentations: "Apresentações",
  reports: "Relatórios",
  brochures: "Brochuras",
  publications: "Publicações",
  print: "Material impresso",
  environment: "Espaço",
  objects: "Objectos",
  advertising: "Publicidade",
  posters: "Cartazes",
  launches: "Lançamentos",
  events: "Eventos",
  few: "Algumas aplicações-chave",
  smallSet: "Um conjunto pequeno",
  broad: "Um leque alargado",
  many: "Muitas aplicações, em contextos diferentes",
  eventIdentity: "Identidade de evento",
  keyVisual: "Key visual",
  campaignLanguage: "Linguagem visual de campanha",
  posterCampaign: "Campanha de cartaz / impressão",
  digitalCampaign: "Campanha digital",
  fullCommunication: "Sistema de comunicação completo",
  stage: "Palco / recinto",
  editorial: "Editorial",
  cover: "Capa / artwork de álbum",
  eventArtwork: "Artwork de evento",
  printPiece: "Peça impressa",
  simple: "Simples",
  developed: "Desenvolvida",
  highlyDetailed: "Muito detalhada",
  "1": "1",
  "2-3": "2–3",
  "4-6": "4–6",
  "7+": "7 ou mais",
  motion: "Motion",
  film: "Filme",
  photography: "Fotografia",
  digitalDesign: "Digital",
  development: "Desenvolvimento",
  "3d": "3D",
  writing: "Escrita",
  spatial: "Espaço",
  noDate: "Sem data fixa",
  fewMonths: "Nos próximos meses",
  specificDate: "Tenho uma data concreta",
  quickly: "Precisamos de avançar depressa",
  oneDecisionMaker: "Uma pessoa a decidir",
  smallTeam: "Uma equipa pequena",
  severalStakeholders: "Várias pessoas envolvidas",
  leadership: "Direcção / conselho",
  multipleOrgs: "Várias equipas ou organizações",
  agencyPartner: "Agência / parceiro externo",
  notYet: "Ainda não",
  under3000: "Até €3.000",
  "3000-5000": "€3.000–€5.000",
  "5000-10000": "€5.000–€10.000",
  "10000-20000": "€10.000–€20.000",
  "20000+": "€20.000 ou mais",
} as const;

export const pt: ProjectFlowContent = {
  meta: {
    title: "Falar sobre um projecto · UrsoParvo Studio",
    description:
      "Conte o que está a tentar resolver. Não precisa de um briefing. Respondemos com uma leitura do projecto e os próximos passos.",
  },
  intro: {
    kicker: "Projecto",
    title: "Falar sobre um projecto",
    body: "Não precisa de saber exactamente o que precisa. Escolha o que mais se aproxima.",
  },
  nav: {
    back: "Voltar",
    continue: "Continuar",
    skip: "Agora não",
    edit: "Editar",
    talk: "Falar do projecto",
    send: "Enviar o resumo",
    sending: "A enviar…",
    startAgain: "Começar de novo",
    stepStatus: "{current} de {total}",
  },
  questions: {
    projectType: {
      kicker: "Projecto",
      question: "O que está a tentar resolver?",
      description:
        "Não precisa de um briefing. Escolha o que mais se aproxima.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "identityRedesign",
          label: "A marca já existe e precisa de mudar visualmente",
          description: "Há um logótipo, uma identidade, ou materiais que já não servem.",
        },
        {
          id: "visualIdentity",
          label: "É precisa uma identidade nova",
          description: "Para uma marca que está a nascer, ou que ainda não tem uma cara clara.",
        },
        {
          id: "visualDirection",
          label: "É para um evento, campanha ou lançamento",
          description: "Precisa de uma linguagem visual para um momento concreto.",
        },
        {
          id: "specificAsset",
          label: "É uma peça concreta",
          description: "Um cartaz, uma ilustração, uma capa, um impresso.",
        },
        {
          id: "unsure",
          label: "Ainda não sei bem",
          description: "Sei que algo precisa de mudar. Ainda não sei que projecto é este.",
        },
      ],
    },
    existingBrand: {
      kicker: "O que existe",
      question: "O que é que a marca já tem?",
      description: "Pode escolher mais do que uma. Se não tiver a certeza, não faz mal.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "nameAndBusiness", label: "Um nome e uma actividade" },
        { id: "logo", label: "Um logótipo" },
        { id: "visualIdentity", label: "Uma identidade visual" },
        { id: "disconnectedMaterials", label: "Vários materiais, pouco consistentes entre si" },
        { id: "unsure", label: "Ainda não tenho a certeza" },
      ],
    },
    redesignDepth: {
      kicker: "Âmbito",
      question: "Quanto precisa de mudar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "refine",
          label: "Afinar o que já existe",
          description: "A base é boa. Precisa de mais clareza e consistência.",
        },
        {
          id: "reimagine",
          label: "Mudar de forma visível",
          description: "A marca continua reconhecível, mas o visual precisa de uma mudança nítida.",
        },
        {
          id: "rebuild",
          label: "Repensar o visual de raiz",
          description: "O que existe já não representa a marca.",
        },
      ],
    },
    strategyClarity: {
      kicker: "Direcção",
      question: "A ideia da marca já está definida?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "veryClear",
          label: "Sim, está clara",
          description: "Sabemos quem é e para onde vai.",
        },
        {
          id: "mostlyClear",
          label: "Há um rumo, com coisas por esclarecer",
        },
        {
          id: "stillTakingShape",
          label: "Ainda está a tomar forma",
        },
        {
          id: "unsure",
          label: "Preciso de ajuda a perceber por onde começar",
        },
      ],
    },
    identityScope: {
      kicker: "Identidade",
      question: "O que precisa de fazer parte disto?",
      description: "Escolha o que for relevante. O resto podemos ver depois.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "logo", label: "Logótipo" },
        { id: "symbol", label: "Símbolo" },
        { id: "typography", label: "Tipografia" },
        { id: "colour", label: "Cor" },
        { id: "graphicLanguage", label: "Linguagem gráfica" },
        { id: "illustration", label: "Ilustração" },
        { id: "templates", label: "Modelos para usar no dia-a-dia" },
        { id: "other", label: "Outra coisa" },
      ],
    },
    systemDepth: {
      kicker: "Alcance",
      question: "Até onde deve ir o trabalho?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "foundations",
          label: "O essencial",
          description: "As bases visuais e como usá-las com correcção.",
        },
        {
          id: "system",
          label: "Um sistema que funcione em vários sítios",
          description: "Uma linguagem visual pensada para contextos diferentes.",
        },
        {
          id: "systemAndApplications",
          label: "O sistema e as aplicações principais",
          description: "Além das bases, as peças com que a marca aparece no mundo.",
        },
        {
          id: "completeSystem",
          label: "Um sistema completo, para a equipa continuar a usar",
          description: "Pensado para viver para além deste projecto.",
        },
      ],
    },
    guidelines: {
      kicker: "Orientação",
      question: "Quanta orientação vai ser precisa?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "essential",
          label: labels.essential,
          description: "As regras centrais para um uso correcto.",
        },
        {
          id: "standard",
          label: labels.standard,
          description: "As regras centrais, o comportamento do sistema e as aplicações.",
        },
        {
          id: "detailed",
          label: labels.detailed,
          description: "Um documento completo, pensado para uso interno continuado.",
        },
      ],
    },
    applications: {
      kicker: "Onde aparece",
      question: "Onde é que isto precisa de aparecer?",
      description: "Escolha os sítios que importam agora. Não precisa de ser exaustivo.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      groups: [
        {
          id: "digital",
          label: "Digital",
          options: [
            { id: "website", label: "Website" },
            { id: "social", label: "Redes sociais" },
            { id: "presentations", label: "Apresentações" },
          ],
        },
        {
          id: "editorial",
          label: "Impresso",
          options: [
            { id: "print", label: "Material impresso" },
            { id: "publications", label: "Publicações" },
          ],
        },
        {
          id: "physical",
          label: "Físico",
          options: [
            { id: "packaging", label: "Embalagem" },
            { id: "signage", label: "Sinalética" },
            { id: "environment", label: "Espaço" },
            { id: "merchandise", label: "Merchandising" },
          ],
        },
        {
          id: "campaigns",
          label: "Campanha",
          options: [
            { id: "advertising", label: "Publicidade" },
            { id: "posters", label: "Cartazes" },
            { id: "events", label: "Eventos" },
          ],
        },
      ],
    },
    applicationScale: {
      kicker: "Escala",
      question: "Quão extensas são as aplicações?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "few", label: labels.few },
        { id: "smallSet", label: labels.smallSet },
        { id: "broad", label: labels.broad },
        { id: "many", label: labels.many },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    campaignKind: {
      kicker: "Campanha",
      question: "O que estamos a criar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "eventIdentity", label: "A cara visual de um evento" },
        { id: "keyVisual", label: "Uma imagem principal" },
        { id: "campaignLanguage", label: "Uma linguagem para a campanha" },
        { id: "posterCampaign", label: "Uma campanha de cartaz" },
        { id: "digitalCampaign", label: "Uma campanha digital" },
        { id: "fullCommunication", label: "Um sistema de comunicação completo" },
        { id: "other", label: "Outra coisa" },
      ],
    },
    campaignPlacements: {
      kicker: "Onde aparece",
      question: "Onde é que isto vai aparecer?",
      description: "Pode escolher mais do que um sítio.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "posters", label: "Cartazes" },
        { id: "social", label: "Redes sociais" },
        { id: "website", label: "Website" },
        { id: "advertising", label: "Publicidade" },
        { id: "signage", label: "Sinalética" },
        { id: "stage", label: "Palco / recinto" },
        { id: "merchandise", label: "Merchandising" },
        { id: "editorial", label: "Impresso" },
        { id: "other", label: "Outro" },
      ],
    },
    specificKind: {
      kicker: "Peça",
      question: "Que peça é esta?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "illustration", label: "Ilustração" },
        { id: "poster", label: "Cartaz" },
        { id: "editorial", label: "Imagem para uma publicação" },
        { id: "cover", label: "Capa" },
        { id: "packaging", label: "Embalagem" },
        { id: "eventArtwork", label: "Imagem para um evento" },
        { id: "printPiece", label: "Outro impresso" },
        { id: "other", label: "Outra coisa" },
      ],
    },
    imageComplexity: {
      kicker: "Imagem",
      question: "Quão complexa é a imagem?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "simple", label: labels.simple },
        { id: "developed", label: labels.developed },
        { id: "highlyDetailed", label: labels.highlyDetailed },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    pieceCount: {
      kicker: "Quantidade",
      question: "Quantas peças finais?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "1", label: "Uma" },
        { id: "2-3", label: "Duas ou três" },
        { id: "4-6", label: "Quatro a seis" },
        { id: "7+", label: "Sete ou mais" },
      ],
    },
    specialists: {
      kicker: "À volta",
      question: "O projecto precisa de mais alguma coisa além do visual?",
      description: "Só o que for preciso. Se não for o caso, continue.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "motion",
          label: "Movimento",
          description: "Animação, ou a identidade em movimento.",
        },
        {
          id: "film",
          label: "Filme",
          description: "Vídeo, filmagem ou montagem.",
        },
        {
          id: "photography",
          label: "Fotografia",
        },
        {
          id: "digitalDesign",
          label: "Website",
          description: "O desenho de uma página ou de uma experiência digital.",
        },
        {
          id: "development",
          label: "Programação",
          description: "Fazer o site ou a peça digital funcionar.",
        },
        {
          id: "3d",
          label: "3D",
        },
        {
          id: "writing",
          label: "Texto",
          description: "Nome, palavras, tom de voz.",
        },
        {
          id: "spatial",
          label: "Espaço",
          description: "Sinalética, ou a marca num sítio físico.",
        },
      ],
    },
    timeline: {
      kicker: "Calendário",
      question: "Há uma data em vista?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "noDate", label: "Ainda não" },
        { id: "fewMonths", label: "Nos próximos meses" },
        { id: "specificDate", label: "Sim, há uma data concreta" },
        { id: "quickly", label: "Precisamos de avançar depressa" },
      ],
    },
    targetDate: {
      kicker: "Calendário",
      question: "Qual é a data?",
      dateLabel: "Quando precisa disto?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
    },
    stakeholders: {
      kicker: "Pessoas",
      question: "Quem decide neste projecto?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "oneDecisionMaker", label: "Uma pessoa" },
        { id: "smallTeam", label: "Uma equipa pequena" },
        { id: "severalStakeholders", label: "Várias pessoas a decidir" },
        { id: "multipleOrgs", label: "Várias equipas ou organizações" },
      ],
    },
    budget: {
      kicker: "Investimento",
      question: "Já tem uma ordem de grandeza em mente?",
      helper: "Não precisa de ser exacto. Ajuda-nos a perceber a escala.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "notYet", label: "Ainda não" },
        { id: "under3000", label: labels.under3000 },
        { id: "3000-5000", label: labels["3000-5000"] },
        { id: "5000-10000", label: labels["5000-10000"] },
        { id: "10000-20000", label: labels["10000-20000"] },
        { id: "20000+", label: labels["20000+"] },
      ],
    },
    description: {
      kicker: "Contexto",
      question: "O que está a acontecer — e o que gostaria que fosse diferente?",
      placeholder: "Pode ser informal. Não precisa de estar definido.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
    },
  },
  review: {
    kicker: "Leitura",
    title: "O seu projecto",
    empty: "Por definir",
    continueLabel: "Continuar",
  },
  estimate: {
    kicker: "Leitura",
    seeing: "É isto que estamos a ver.",
    initial: "Estimativa inicial",
    indicative: "Estimativa indicativa",
    lowTitle: "Este projecto precisa de uma conversa.",
    lowBody:
      "Ainda não dá para avançar um número com responsabilidade — e está tudo bem começar assim. O passo seguinte é falarmos.",
    refinement:
      "Parte do que descreveu acima. Afinamos quando falarmos do projecto com calma.",
    specialists:
      "Pode fazer sentido trazer gente de {list} para o projecto, se for útil.",
    talk: "Falar do projecto",
    edit: "Editar",
    preparing: "A preparar…",
    scale: {
      contained: "escala contida",
      medium: "escala média",
      mediumLarge: "âmbito médio a largo",
      large: "âmbito largo",
    },
  },
  contact: {
    kicker: "Contacto",
    question: "Para onde enviamos o resumo?",
    name: "Nome",
    email: "Email",
    company: "Empresa / organização",
    website: "Website",
    phone: "Telefone",
    optional: "opcional",
    nameError: "Precisamos de um nome para sabermos com quem estamos a falar.",
    emailError: "Precisamos de um email para enviar o resumo do projecto.",
  },
  complete: {
    kicker: "Enviado",
    title: "Recebemos o projecto.",
    body: "Vamos lê-lo e responder com os próximos passos.",
    home: "Voltar ao início",
  },
  errors: {
    submit:
      "Algo impediu o envio do projecto. As respostas continuam aqui. Tente de novo.",
    estimate: "Não foi possível preparar a estimativa. As respostas continuam aqui.",
    choose: "Escolha uma opção para continuar.",
  },
  classifications: {
    identityRefresh: "um afinamento da identidade visual",
    identityRedesign: "um redesign de identidade visual",
    identitySystem: "um sistema de identidade visual",
    visualIdentity: "uma identidade visual nova",
    campaignEvent: "uma direcção visual para evento ou campanha",
    keyVisual: "uma imagem principal para campanha",
    specificGraphic: "uma peça gráfica específica",
    needsConversation: "um projecto ainda a definir",
  },
  assumptions: {
    scopeDescribed: "A estimativa parte do âmbito descrito acima.",
    estimateNotBinding:
      "É uma estimativa inicial, não uma cotação. A proposta fecha-se depois de falarmos do projecto.",
    strategyPartiallyDefined: "A direcção estratégica parece parcialmente definida.",
    strategyUndefined: "A direcção ainda está a tomar forma.",
    specialistsIntegrated:
      "Há extensões especializadas que podem entrar no projecto quando forem úteis.",
    discoveryRecommended: "Convém uma conversa antes de fechar âmbito e valores.",
    applicationsUncertain: "A extensão das aplicações ainda não está clara.",
    timelineFlexible: "Não há uma data fixa a condicionar o calendário.",
  },
  confidence: {
    high: "Alta",
    medium: "Média",
    low: "Baixa",
  },
  labels: {
    ...labels,
    visualIdentityExisting: "Uma identidade visual",
    logoMark: "Um logótipo",
    poster: "Cartaz",
    "pieces:1": "1 peça final",
    "pieces:2-3": "2–3 peças finais",
    "pieces:4-6": "4–6 peças finais",
    "pieces:7+": "7 ou mais peças finais",
  },
  brief: {
    project: "PROJECTO",
    overview: "ENQUADRAMENTO",
    scope: "ÂMBITO",
    applications: "APLICAÇÕES",
    extensions: "EXTENSÕES",
    timeline: "CALENDÁRIO",
    budget: "INVESTIMENTO",
    initialEstimate: "ESTIMATIVA INICIAL",
    confidence: "CONFIANÇA",
    notes: "NOTAS",
    contact: "CONTACTO",
    none: "Nenhuma",
    notSpecified: "Por definir",
    toBeDiscussed: "A discutir",
    labels: {
      ...labels,
      visualIdentity: "Criar uma identidade visual",
      logo: "Logótipo / wordmark",
      poster: "Cartaz",
      "pieces:1": "1 peça final",
      "pieces:2-3": "2–3 peças finais",
      "pieces:4-6": "4–6 peças finais",
      "pieces:7+": "7 ou mais peças finais",
      visualIdentityExisting: "Uma identidade visual",
      logoMark: "Um logótipo",
    },
    confidenceLabels: {
      high: "Alta",
      medium: "Média",
      low: "Baixa",
    },
  },
  stepAria: {},
};
