import type { ProjectFlowContent } from "./types";

const labels = {
  identityRedesign: "Redesenhar uma marca existente",
  visualIdentity: "Criar uma identidade visual",
  visualDirection: "Criar uma direcção visual",
  specificAsset: "Criar algo específico",
  unsure: "Ainda não sei",
  nameAndBusiness: "Um nome e uma actividade",
  logo: "Logótipo / wordmark",
  visualIdentityState: "Uma identidade visual",
  fullVisualSystem: "Um sistema visual completo",
  identityNoLongerWorks: "Uma identidade que já não funciona",
  disconnectedMaterials: "Materiais visuais desligados entre si",
  refine: "Afinar",
  reimagine: "Reimaginar",
  rebuild: "Reconstruir",
  veryClear: "Muito clara",
  mostlyClear: "Em grande parte clara",
  stillTakingShape: "Ainda a tomar forma",
  symbol: "Símbolo / marca",
  typography: "Tipografia",
  colour: "Sistema de cor",
  graphicLanguage: "Linguagem gráfica",
  illustration: "Ilustração",
  iconography: "Iconografia",
  photographyDirection: "Direcção fotográfica",
  layoutSystem: "Sistema de composição",
  templates: "Modelos",
  packaging: "Embalagem",
  signage: "Sinalética",
  merchandise: "Merchandising",
  other: "Outro",
  foundations: "Fundações",
  system: "Sistema",
  systemAndApplications: "Sistema e aplicações",
  completeSystem: "Sistema completo",
  essential: "Essencial",
  standard: "Padrão",
  detailed: "Detalhado",
  website: "Website",
  social: "Redes sociais",
  email: "Email",
  digitalProducts: "Produtos digitais",
  presentations: "Apresentações",
  reports: "Relatórios",
  brochures: "Brochuras",
  publications: "Publicações",
  print: "Material impresso",
  environment: "Espaço",
  objects: "Objectos",
  advertising: "Publicidade",
  posters: "Cartazes",
  launches: "Lançamentos",
  events: "Eventos",
  few: "Algumas aplicações-chave",
  smallSet: "Um conjunto pequeno",
  broad: "Um leque alargado",
  many: "Muitas aplicações, em contextos diferentes",
  eventIdentity: "Identidade de evento",
  keyVisual: "Key visual",
  campaignLanguage: "Linguagem visual de campanha",
  posterCampaign: "Campanha de cartaz / impressão",
  digitalCampaign: "Campanha digital",
  fullCommunication: "Sistema de comunicação completo",
  stage: "Palco / recinto",
  editorial: "Editorial",
  cover: "Capa / artwork de álbum",
  eventArtwork: "Artwork de evento",
  printPiece: "Peça impressa",
  simple: "Simples",
  developed: "Desenvolvida",
  highlyDetailed: "Muito detalhada",
  "1": "1",
  "2-3": "2–3",
  "4-6": "4–6",
  "7+": "7 ou mais",
  motion: "Motion",
  film: "Filme",
  photography: "Fotografia",
  digitalDesign: "Digital",
  development: "Desenvolvimento",
  "3d": "3D",
  writing: "Escrita",
  spatial: "Espaço",
  noDate: "Sem data fixa",
  fewMonths: "Nos próximos meses",
  specificDate: "Tenho uma data concreta",
  quickly: "Precisamos de avançar depressa",
  oneDecisionMaker: "Uma pessoa a decidir",
  smallTeam: "Uma equipa pequena",
  severalStakeholders: "Várias pessoas envolvidas",
  leadership: "Direcção / conselho",
  multipleOrgs: "Várias equipas ou organizações",
  agencyPartner: "Agência / parceiro externo",
  notYet: "Ainda não",
  under3000: "Até €3.000",
  "3000-5000": "€3.000–€5.000",
  "5000-10000": "€5.000–€10.000",
  "10000-20000": "€10.000–€20.000",
  "20000+": "€20.000 ou mais",
} as const;

export const pt: ProjectFlowContent = {
  meta: {
    title: "Falar sobre um projecto · UrsoParvo Studio",
    description:
      "Conte-nos o que precisa de mudar, criar ou comunicar. Respondemos com uma leitura clara do projecto e uma estimativa inicial.",
  },
  intro: {
    kicker: "Projecto",
    title: "Falar sobre um projecto",
    body: "Algumas perguntas para percebermos o que está em causa. Não é preciso ter tudo definido.",
  },
  nav: {
    back: "Voltar",
    continue: "Continuar",
    edit: "Editar",
    talk: "Falar sobre o projecto",
    send: "Enviar o resumo",
    sending: "A enviar…",
    startAgain: "Começar de novo",
    stepStatus: "Passo {current} de {total}",
  },
  questions: {
    projectType: {
      kicker: "Projecto",
      question: "Em que vamos trabalhar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "identityRedesign",
          label: labels.identityRedesign,
          description: "A marca existe, mas a identidade visual precisa de evoluir.",
        },
        {
          id: "visualIdentity",
          label: labels.visualIdentity,
          description: "É precisa uma identidade nova, para uma marca existente ou a nascer.",
        },
        {
          id: "visualDirection",
          label: labels.visualDirection,
          description:
            "Uma campanha, evento, festival, lançamento ou comunicação precisa de uma linguagem visual.",
        },
        {
          id: "specificAsset",
          label: labels.specificAsset,
          description:
            "Uma peça gráfica, ilustração, cartaz, publicação, objecto ou outro material visual.",
        },
        {
          id: "unsure",
          label: labels.unsure,
          description: "Sei que algo precisa de mudar, mas ainda não sei que projecto é este.",
        },
      ],
    },
    existingBrand: {
      kicker: "O que existe",
      question: "O que já existe?",
      description: "Pode escolher mais do que uma resposta.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "nameAndBusiness", label: labels.nameAndBusiness },
        { id: "logo", label: "Um logótipo" },
        { id: "visualIdentity", label: "Uma identidade visual" },
        { id: "fullVisualSystem", label: labels.fullVisualSystem },
        { id: "identityNoLongerWorks", label: labels.identityNoLongerWorks },
        { id: "disconnectedMaterials", label: labels.disconnectedMaterials },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    redesignDepth: {
      kicker: "Âmbito",
      question: "Quanto precisa de mudar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "refine",
          label: labels.refine,
          description:
            "A identidade tem uma base sólida. Precisa de clareza, consistência ou afinação.",
        },
        {
          id: "reimagine",
          label: labels.reimagine,
          description:
            "A marca continua reconhecível, mas a expressão visual precisa de uma mudança significativa.",
        },
        {
          id: "rebuild",
          label: labels.rebuild,
          description:
            "A identidade actual já não reflecte a marca e precisa de ser repensada a sério, no plano visual.",
        },
      ],
    },
    strategyClarity: {
      kicker: "Direcção",
      question: "Quão clara está já a direcção?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "veryClear",
          label: labels.veryClear,
          description: "O posicionamento e a direcção já estão definidos.",
        },
        {
          id: "mostlyClear",
          label: labels.mostlyClear,
          description: "Há uma direcção, mas ainda há coisas a esclarecer.",
        },
        {
          id: "stillTakingShape",
          label: labels.stillTakingShape,
          description: "A própria marca ainda está a ser definida.",
        },
        {
          id: "unsure",
          label: "Não tenho a certeza",
          description: "Preciso de ajuda a perceber por onde começar.",
        },
      ],
    },
    identityScope: {
      kicker: "Identidade",
      question: "O que precisa de fazer parte da identidade?",
      description: "Escolha o que for relevante. Não é uma lista de compras.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "logo", label: labels.logo },
        { id: "symbol", label: labels.symbol },
        { id: "typography", label: labels.typography },
        { id: "colour", label: labels.colour },
        { id: "graphicLanguage", label: labels.graphicLanguage },
        { id: "illustration", label: labels.illustration },
        { id: "iconography", label: labels.iconography },
        { id: "photographyDirection", label: labels.photographyDirection },
        { id: "layoutSystem", label: labels.layoutSystem },
        { id: "templates", label: labels.templates },
        { id: "packaging", label: labels.packaging },
        { id: "signage", label: labels.signage },
        { id: "merchandise", label: labels.merchandise },
        { id: "other", label: labels.other },
      ],
    },
    systemDepth: {
      kicker: "Sistema",
      question: "Até onde deve ir o sistema visual?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "foundations",
          label: labels.foundations,
          description: "Os elementos visuais centrais e as regras de uso.",
        },
        {
          id: "system",
          label: labels.system,
          description: "Uma linguagem visual pensada para funcionar em contextos diferentes.",
        },
        {
          id: "systemAndApplications",
          label: labels.systemAndApplications,
          description: "O sistema visual e as suas aplicações principais no mundo real.",
        },
        {
          id: "completeSystem",
          label: labels.completeSystem,
          description:
            "Um sistema de identidade robusto, pensado para continuar a ser usado por uma equipa mais larga.",
        },
      ],
    },
    guidelines: {
      kicker: "Orientação",
      question: "Quanta orientação vai ser precisa?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "essential",
          label: labels.essential,
          description: "As regras centrais para um uso correcto.",
        },
        {
          id: "standard",
          label: labels.standard,
          description: "As regras centrais, o comportamento do sistema e as aplicações.",
        },
        {
          id: "detailed",
          label: labels.detailed,
          description: "Um documento completo, pensado para uso interno continuado.",
        },
      ],
    },
    applications: {
      kicker: "Contextos",
      question: "Onde é que a identidade precisa de funcionar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      groups: [
        {
          id: "digital",
          label: "Digital",
          options: [
            { id: "website", label: labels.website },
            { id: "social", label: labels.social },
            { id: "email", label: labels.email },
            { id: "digitalProducts", label: labels.digitalProducts },
            { id: "presentations", label: labels.presentations },
          ],
        },
        {
          id: "editorial",
          label: "Editorial",
          options: [
            { id: "reports", label: labels.reports },
            { id: "brochures", label: labels.brochures },
            { id: "publications", label: labels.publications },
            { id: "print", label: labels.print },
          ],
        },
        {
          id: "physical",
          label: "Físico",
          options: [
            { id: "packaging", label: labels.packaging },
            { id: "signage", label: labels.signage },
            { id: "environment", label: labels.environment },
            { id: "merchandise", label: labels.merchandise },
            { id: "objects", label: labels.objects },
          ],
        },
        {
          id: "campaigns",
          label: "Campanhas",
          options: [
            { id: "advertising", label: labels.advertising },
            { id: "posters", label: labels.posters },
            { id: "launches", label: labels.launches },
            { id: "events", label: labels.events },
          ],
        },
      ],
    },
    applicationScale: {
      kicker: "Escala",
      question: "Quão extensas são as aplicações?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "few", label: labels.few },
        { id: "smallSet", label: labels.smallSet },
        { id: "broad", label: labels.broad },
        { id: "many", label: labels.many },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    campaignKind: {
      kicker: "Campanha",
      question: "O que estamos a criar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "eventIdentity", label: labels.eventIdentity },
        { id: "keyVisual", label: labels.keyVisual },
        { id: "campaignLanguage", label: labels.campaignLanguage },
        { id: "posterCampaign", label: labels.posterCampaign },
        { id: "digitalCampaign", label: labels.digitalCampaign },
        { id: "fullCommunication", label: labels.fullCommunication },
        { id: "other", label: labels.other },
      ],
    },
    campaignPlacements: {
      kicker: "Contextos",
      question: "Onde vai viver?",
      description: "Pode escolher mais do que um contexto.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "posters", label: labels.posters },
        { id: "social", label: labels.social },
        { id: "website", label: labels.website },
        { id: "advertising", label: labels.advertising },
        { id: "signage", label: labels.signage },
        { id: "stage", label: labels.stage },
        { id: "merchandise", label: labels.merchandise },
        { id: "editorial", label: labels.editorial },
        { id: "other", label: labels.other },
      ],
    },
    specificKind: {
      kicker: "Peça",
      question: "O que estamos a fazer?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "illustration", label: labels.illustration },
        { id: "poster", label: "Cartaz" },
        { id: "editorial", label: "Artwork editorial" },
        { id: "cover", label: labels.cover },
        { id: "packaging", label: "Artwork de embalagem" },
        { id: "eventArtwork", label: labels.eventArtwork },
        { id: "printPiece", label: labels.printPiece },
        { id: "other", label: labels.other },
      ],
    },
    imageComplexity: {
      kicker: "Imagem",
      question: "Quão complexa é a imagem?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "simple", label: labels.simple },
        { id: "developed", label: labels.developed },
        { id: "highlyDetailed", label: labels.highlyDetailed },
        { id: "unsure", label: "Não tenho a certeza" },
      ],
    },
    pieceCount: {
      kicker: "Quantidade",
      question: "Quantas peças finais?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "1", label: "Uma" },
        { id: "2-3", label: "2–3" },
        { id: "4-6", label: "4–6" },
        { id: "7+", label: "7 ou mais" },
      ],
    },
    specialists: {
      kicker: "Extensões",
      question: "O projecto pode ir além do design visual?",
      description:
        "Não é uma lista de extras. São necessidades possíveis, se fizerem parte do projecto.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        {
          id: "motion",
          label: labels.motion,
          description: "Animação, identidade em movimento ou peças animadas.",
        },
        {
          id: "film",
          label: labels.film,
          description: "Vídeo, filmagem, montagem ou campanhas audiovisuais.",
        },
        {
          id: "photography",
          label: labels.photography,
          description: "Produção fotográfica ou direcção de arte fotográfica.",
        },
        {
          id: "digitalDesign",
          label: labels.digitalDesign,
          description: "Design de website, landing pages ou experiências digitais.",
        },
        {
          id: "development",
          label: labels.development,
          description: "Desenvolvimento web ou implementação técnica.",
        },
        {
          id: "advertising",
          label: labels.advertising,
          description: "Desenvolvimento de campanha e peças publicitárias.",
        },
        {
          id: "3d",
          label: labels["3d"],
          description: "Imagem 3D, renders ou animação.",
        },
        {
          id: "writing",
          label: labels.writing,
          description: "Naming, copywriting ou identidade verbal.",
        },
        {
          id: "spatial",
          label: labels.spatial,
          description: "Gráfica de espaço, sinalética ou experiências físicas.",
        },
      ],
    },
    timeline: {
      kicker: "Calendário",
      question: "Há uma data para a qual precisamos de trabalhar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "noDate", label: labels.noDate },
        { id: "fewMonths", label: labels.fewMonths },
        { id: "specificDate", label: labels.specificDate },
        { id: "quickly", label: labels.quickly },
      ],
    },
    targetDate: {
      kicker: "Calendário",
      question: "Qual é a data?",
      dateLabel: "Data",
      continueLabel: "Continuar",
      backLabel: "Voltar",
    },
    stakeholders: {
      kicker: "Processo",
      question: "Quem vai estar envolvido no processo?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "oneDecisionMaker", label: labels.oneDecisionMaker },
        { id: "smallTeam", label: labels.smallTeam },
        { id: "severalStakeholders", label: labels.severalStakeholders },
        { id: "leadership", label: labels.leadership },
        { id: "multipleOrgs", label: labels.multipleOrgs },
        { id: "agencyPartner", label: labels.agencyPartner },
      ],
    },
    budget: {
      kicker: "Investimento",
      question: "Já tem um intervalo de investimento em mente?",
      helper:
        "Não precisa de ser exacto. Ajuda-nos a perceber a escala que está a considerar.",
      continueLabel: "Continuar",
      backLabel: "Voltar",
      options: [
        { id: "notYet", label: labels.notYet },
        { id: "under3000", label: labels.under3000 },
        { id: "3000-5000", label: labels["3000-5000"] },
        { id: "5000-10000", label: labels["5000-10000"] },
        { id: "10000-20000", label: labels["10000-20000"] },
        { id: "20000+", label: labels["20000+"] },
      ],
    },
    description: {
      kicker: "Contexto",
      question: "Conte-nos um pouco sobre o projecto.",
      placeholder: "O que está a tentar mudar, criar ou comunicar?",
      continueLabel: "Continuar",
      backLabel: "Voltar",
    },
  },
  review: {
    kicker: "Leitura",
    title: "O seu projecto",
    empty: "Por definir",
    continueLabel: "Continuar",
  },
  estimate: {
    kicker: "Leitura",
    seeing: "Isto é o que estamos a ver.",
    initial: "Estimativa inicial",
    indicative: "Estimativa indicativa",
    lowTitle: "Este projecto precisa de uma conversa.",
    lowBody:
      "Ainda não temos informação suficiente para o estimar com responsabilidade. O passo seguinte é falarmos.",
    refinement:
      "Esta estimativa parte do âmbito descrito acima. Podemos afiná-la quando entendermos o projecto com mais detalhe.",
    specialists:
      "O projecto pode envolver colaboradores especializados em {list}. Integram-se quando for útil.",
    talk: "Falar sobre o projecto",
    edit: "Editar projecto",
    scale: {
      contained: "escala contida",
      medium: "escala média",
      mediumLarge: "âmbito médio a largo",
      large: "âmbito largo",
    },
  },
  contact: {
    kicker: "Contacto",
    question: "Para onde devemos enviar o resumo do projecto?",
    name: "Nome",
    email: "Email",
    company: "Empresa / organização",
    website: "Website",
    phone: "Telefone",
    optional: "opcional",
    nameError: "Indique um nome para sabermos com quem estamos a falar.",
    emailError: "Indique um email para sabermos para onde enviar o resumo do projecto.",
  },
  complete: {
    kicker: "Enviado",
    title: "Recebemos o projecto.",
    body: "Lemos o que enviou e respondemos para o email que indicou.",
    home: "Voltar ao início",
  },
  errors: {
    submit:
      "Algo impediu o envio do projecto. As respostas continuam aqui. Tente de novo.",
    estimate: "Não foi possível preparar a estimativa. As respostas continuam aqui.",
  },
  classifications: {
    identityRefresh: "afinamento de identidade visual",
    identityRedesign: "redesign de identidade visual",
    identitySystem: "sistema de identidade visual",
    visualIdentity: "identidade visual nova",
    campaignEvent: "direcção visual para evento ou campanha",
    keyVisual: "key visual",
    specificGraphic: "peça gráfica específica",
    needsConversation: "projecto ainda a definir",
  },
  assumptions: {
    scopeDescribed: "A estimativa parte do âmbito descrito acima.",
    estimateNotBinding:
      "É uma estimativa inicial, não uma cotação. A proposta fecha-se depois de falarmos do projecto.",
    strategyPartiallyDefined: "A direcção estratégica parece parcialmente definida.",
    strategyUndefined: "A direcção ainda está a tomar forma.",
    specialistsIntegrated:
      "Há extensões especializadas que podem entrar no projecto quando forem úteis.",
    discoveryRecommended: "Convém uma conversa antes de fechar âmbito e valores.",
    applicationsUncertain: "A extensão das aplicações ainda não está clara.",
    timelineFlexible: "Não há uma data fixa a condicionar o calendário.",
  },
  confidence: {
    high: "Alta",
    medium: "Média",
    low: "Baixa",
  },
  labels: {
    ...labels,
    visualIdentityExisting: "Uma identidade visual",
    logoMark: "Um logótipo",
    poster: "Cartaz",
    "pieces:1": "1 peça final",
    "pieces:2-3": "2–3 peças finais",
    "pieces:4-6": "4–6 peças finais",
    "pieces:7+": "7 ou mais peças finais",
  },
  brief: {
    project: "PROJECTO",
    overview: "ENQUADRAMENTO",
    scope: "ÂMBITO",
    applications: "APLICAÇÕES",
    extensions: "EXTENSÕES",
    timeline: "CALENDÁRIO",
    budget: "INVESTIMENTO",
    initialEstimate: "ESTIMATIVA INICIAL",
    confidence: "CONFIANÇA",
    notes: "NOTAS",
    contact: "CONTACTO",
    none: "Nenhuma",
    notSpecified: "Por definir",
    toBeDiscussed: "A discutir",
    labels: {
      ...labels,
      visualIdentity: "Criar uma identidade visual",
      logo: "Logótipo / wordmark",
      poster: "Cartaz",
      "pieces:1": "1 peça final",
      "pieces:2-3": "2–3 peças finais",
      "pieces:4-6": "4–6 peças finais",
      "pieces:7+": "7 ou mais peças finais",
      visualIdentityExisting: "Uma identidade visual",
      logoMark: "Um logótipo",
    },
    confidenceLabels: {
      high: "Alta",
      medium: "Média",
      low: "Baixa",
    },
  },
  stepAria: {},
};
